# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: docker-regcred
    namespace: flux-system
data:
    .dockerconfigjson: ENC[AES256_GCM,data:M3VDjsVCkrU00lq+BlrJ2uZSBlsxg5eQzORKn8b/o+OCxkTLKKzVF5VUwlWYWGo6rM0wf166FfXWN5gV7ER41WQBa5YLvZVc2n0oXs9YjxAmVQ2aiK3/ubqLiYB9M+f93ZjYkztkkDC3u7GHIeBPF9m/tSC9TOHg6VRJhobi806bYeQj3/YkqAasy5KkrgMGB8KJaZOYBahcKIfUnGNw82TYDNamoJi7R1tkFLVqQZykup7yE+N39DWIuXZR1DFyG3mLIJLng9/No64fjT7HLiGCAHJoqV9NIb0flB7jyla0UGs1pUPcyRhpr0NBIP5wydlpCA==,iv:huuAt2/ypZyJZCPA6Q959rw99Lz3u8aKm92Ml7fBnQY=,tag:iV6FKUPNdEOhBUbcOnWpWA==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VG9kTUVlWXZXLy80ZE9T
            WmhLSUI5YVZLdVhmTit6c293U1ZxSmRyaDJRCkc3Qm1raUFQSnJKdzF0cVFtaUhN
            NjJhVERGN2swNzZmbDRlSUxQR08yQ00KLS0tIFMyR1E0K1hRc0M5Vnd2T212NEVk
            SlVueENFRXRzaW82RWc5OWh5RE50aDAKHE928Hi6y4GN0sJVucgWaoJ/OmGMtZwr
            SzyIPvi2eeuyUoZuhmfV2BbcjyEI9SvbNLPOYBEH8b7OtotHjn0paw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T21:13:07Z"
    mac: ENC[AES256_GCM,data:COYbh7uck6N2Lb5AXl/xJZMiHRM1HvoCO844VPckRwaqDgtLIhdrOKHOmNdWEEuykJT5NJ3eRllxKjkoiIZ7yJPN5UbTvmA3aWdlStEjPhTA63yiqwxYuqjlA3uCaFtAKZM6eiuko9KxHs35A1J1hVofMb+GkeYMDbtc/qGEBZ0=,iv:/oWVP5FpiQi4KcrZvMI0tKSZG1lKwgt3dg+iQ4y1SUc=,tag:VeaOIqbRCu5YabAa7dG3Ig==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
