# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: docker-regcred
    namespace: default
data:
    .dockerconfigjson: ENC[AES256_GCM,data:mZ8IZv4dqdvPmmrYc4mlgERuvSdVxDEQdvAzM1zIDqRflBCIYQQIjCyHSl0246qafKXqv00pWMzv/jTpRdjZH44rP2NbSovilzb163aumRc/WnxR3HEDt5bBSpsRG+dtcE/7vysSaLXFOjNVsfspYcNlMYBqVAr2i//A5lRoW6uHU6GfMzJF3ZOpRTAJCnR/GpXotpFAm7kViUWtUxh1+DGsR1a0MYinjmLHPOUpVMBZHOnwtogvrG2b81MNthzb9p/4wKTMy3qSgqVCxwbJQthQ9RpURR2ZoZknwMQ7O0Qg8n4z4mEAU3c1nis8bZOMYBdNVw==,iv:uNckuXVdkZcI+t6kw9ej/ivetJnS7uTI/TB67lP0Q+8=,tag:ETVCJMDaX6cWam0DdEBCYQ==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMHhjb3hjLzk5aVdEOVU2
            K0RlVmhmUU1pb01DdHNCT2djM3VLWVhqSGxRClgzS0IreTJxdFUxTXZHZXNKRnMw
            L3E1eUErcjB6UlBtZ2Vsano3SzhpaGsKLS0tIDNPS1NXMzFXU0J1T0t1czVaNjEx
            L1VlWWpQNWVyVnRDZExWRlIrRjR3dmMKQPl+fYrVS8uh6t8qL+D19XyfWm0h3Kbu
            7oZqqck18fy2a5hk97XvG5L7DceMxHELxvVe4CySTTI9Db2nh71Fng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:28:46Z"
    mac: ENC[AES256_GCM,data:t8+C4YCymNESJKR8KVn8o/PEp7ejNCy/t96KU3pgOh01kOdyKUO1Q4Nw5RGvY3EcoFLYoZfIXcdZlMVySh/MwFvZjzkSkFneucnyW7+PU1BeVK63PxWntM6Oil65jiEbxU63jDNdYyYPz1b4REHch0qsNkUPaOiXiq69qtBWOps=,iv:0YeLyYe5xXPhSACE6JuUIg52KUA1EddlsdrHQ0RGZ24=,tag:w7kOCcdO2gJtExkc7C0Vzw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
