# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: docker-regcred
    namespace: flux-system
data:
    .dockerconfigjson: ENC[AES256_GCM,data:1L2DGp/FkbB2moHT6zr69/HjYc3H7kyzQpcryu7A+5k3cc8zwzqDxSDNDPHV5GCFLCJyDFhqYyoUvRfLPjvos6GIYOK/y7xiA/Hvc5VXhlJcvtOcJQY2K21H7EDjzASXzOZmZUytkWvs+x6SASkemKkJ3UNeWtpxLININLS3vXH37KxvxRtaOTEaQrbug7EiOemcm/mGNDe2uqoHV+gsFyXE1ufBwtgNqzDqUUKrGfMVVvE2viKuQ2/F06wUzuVaEAOHw/xD0EvO6IK3TjLMenD7FbtD+8IXtpmsdd4wSsqb7jdgHr0wKNhigVJVvL0yFn1Meg==,iv:stOqcZMAGVvmfh/5HKoEM1+4fJsvuvbmwtCKAnApy7I=,tag:T/t14plHjebawt9fwZdyWA==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbTMxRkloK3hWRktvZC9J
            WnFmV3FlaHd5anBpRmR5TUV1MVEzZjVoQkQwCnVCMzQrczJndHdjeFJjVUF0YTdx
            VHBwZCtTUi9DUDFxcW1Bb0c5TS9CTGsKLS0tIHVMcXJYSG5nSkVuc09oQmFRb0dp
            TU9IVjNVaXdNUkUyQ1dwMWtOTjRhdHMKLnfaKnlc+wqa94R1q8rpPL0ExZ8QQdAD
            g7gr0l1qUVP5/NCPVeRsoJ+TVx9c5XrK1AxvUqqTCyGvpNJG0sPr2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T01:49:11Z"
    mac: ENC[AES256_GCM,data:ZDyX0HNGW+8aoj6M2efOIy2upkhRAfSN9NKksw8+wR20yydVI/vDhFjp+0XlzyiIRpk1W25UVRfxd+UPX0mXd7kdNdd9NnADwZiZ3ZlWpk8Qmd2fZ59xalfm7ELcsTOy+2gyqjJ8cEyEqllSr4tYbUK/NInGr2mLer7Nb2dv1rY=,iv:O92lhPLNHsGnutcvtutJAKwi+z5UjlUDAkkQ+0JfrfA=,tag:Y3cXvaJpnYbk3UMDkNBy+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
