# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: git-credentials
    namespace: default
    annotations:
        # Described below
        tekton.dev/git-0: github.com
data:
    id_rsa: ENC[AES256_GCM,data:7Amfwh2zNcRS2XeA8Es0tIxvNBESgfX8QjY1zdAumtUXbGxt0np8Z29b1kxtW8tMUV4EWVl6xNGdJeNT0DF3EIMVjooQ7ZuwCk3JCPT848y4AZW1Ajxqe+mFRlTZruk2K4eLIqEL2woLQvOurB2XpPNeK37jnVPIT9wHm0FFoaG9wFADWpSP6zeDd8eo9i8iR1BYe921kiNm1RgYnd4Vk7TUVLPMHCJ6QkrgkEZFubRFWuJlCTATSb7+x+hpyE24MZQVWQTboWOIPfBUup2Fi5+WpdJaBLUkzAdfCjCrQMLzK89r18OUeBDCuI/V50rvij7nH/MJrGa4OVLLPGU9ZOFflH7gljQiEJNx6EDB1YFW0SWDEInd5G7Ta/GXgiLlwfx55wmkonvF6WB6C36gIHJsk4Gq+4iHcYOWI5upk6W4OiLWMncweE1QXAm6yg/R/tHtHNAkz2ZO2BVjw1c76cL9E1A9kSJ+VpQPsh2vokXqtaaBJpSzovDa1xdSllT1ZMmeF/nUSuGAqUls7yni/lYuqoJG0PfuX+oVL9Vo/F/p1sldSJp8Q698/51AZQMhHvrDJ/vjKIIX8etXCR0PtkOBNUfo3MreMet+sI4bLnT0gOibJe6wH+/hI23aDy3w67K/Krn3IbVUMYS/FN417/vpQ/otpQ34bXvNVmw9nh0XUj0dAaeLKkm/3Vy5/k1jSeY7Gig3zY8ZJIxjX7CxT4ECPKEo7tSHofn0Mumdv6g=,iv:4uK8BX5xh4Vk9dVcvQWKNowgm3nMu9q0U5Kfv6/voks=,tag:KQHFIo/K5jo29hj9lekC3w==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOanNJbUtCcHN1dERtUEdk
            TXhRUFBTdC8valRWQ3dlN0xCU1hVcUdsaHlNCmtUcytXVHNYTEtENkExQi8xWHA5
            T2JxUm1qWWQweVZKeDZIcE5OK2RZU3cKLS0tIGM0OVY1UVUrZTZQdEtMRVJFSU5J
            Q2hlV0JjSnNiMmdGNkpPRW5MWjNKUncKyPkorI6ciyTvQ3TjfWBVzydcImkVJjOC
            5vooeWN8YtzD8PhMYLiEcqOPabEatnrLqbqJ+uatIR4W2t5/ExYGpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T01:49:11Z"
    mac: ENC[AES256_GCM,data:tVgrzVT7QM2Sr1WA/8nANF5E1AwyyGdmWJbmdFeXjCH3TZljsaOxb8YiYPb//OaQ7EYJL4x++yx4FzeK9GHZl+6vfudfQ80mANaP3QiC7g5F6DrkfU0ZdC5TrLfqoNjdT3Ufcm8j8K2SeRLQzsNwpWhFJmKC1ZhkDArIQ/PXygo=,iv:46CWkxuyyu8R/z6Qeo6tjzSjghNWk6CRIp3aD8DV02s=,tag:la/CuWwFvYmEoc3HoIPPrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
