# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: minio-credentials
    namespace: tekton-pipelines
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:HanSsg==,iv:bCcCO1rRvEHCcUI8lz+pviMj0fSb1WFEx33xHUeJr8c=,tag:HkepMcFw++UOdOdPqXe6CA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:3yvYdg==,iv:fDrVgTCUHnQB/rU7Vn8tbSXUv77slNm0q2GmSF/QC4o=,tag:ofUS4rM0Ey1KgTX21OBtLg==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaa21RRitCN3lrSjQrVng2
            TXJLQklQUVk5cWFERGwySEdpQXdjZkJtNWdVClRNcGdRUFFTbGJrMlhhaTdhZWY3
            UWNCUHJGd3N5RGNDdUpDVlhBK2Fyb1EKLS0tIEJhcExLOVJyWjdaYmxMK1FoaytB
            cUIxdkZtVmVDamNiZ3RNVTZsNklYZFkKq68iRyv0L82Ou6f6tT8FCyry0QSwoZ+F
            vXkwlBy4VWWZsuXI/LXAM9jlQbpE0vaPAXcdU2fPLYY2TCmt9Rv8ww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T01:49:11Z"
    mac: ENC[AES256_GCM,data:o+V3n1wOK4lyQyac2zb7nEYCDF8ldzcq7Nk73rXTGYXwMTXrEof8pR5XGpIIjwXJZtBe6ufh7AayfBo3SqrMriL/YsdGnJUCPhvnJlIPtHgySOlF51+Gnr9nxNJtsTwZyiqU1xqhxxdIBOrOZX1oI9qLuhqG4gSjw8lBO4FhGTk=,iv:dMNkmm0EAd9ANWygsiwi6ImybRJAzbA6uXrx6RAaCjw=,tag:mr+QDj43Uncz44VO1B+VeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
