# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.config.k8s.io/kustomization_v1beta1.json
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./minio-upload.yaml
  - ./rust-build.yaml
  - ./git-clone.yaml
  - ./docker-push.yaml
  - ./docker-build.yaml
  - ./opentofu-cli.yaml
  - ./github-pr-comment.yaml
  - https://api.hub.tekton.dev/v1/resource/tekton/task/send-to-webhook-discord/0.1/raw
