# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
stringData:
    client_id: ENC[AES256_GCM,data:gxipMjaCo57mRXcROD1HtAg=,iv:KH0vUWFCNuQkbZLQiA9GikLDKFlhGeOpjM9oOJU+DIQ=,tag:MOPZG0C2bJG57zqaqDNpkA==,type:str]
    client_secret: ENC[AES256_GCM,data:sjbFxcofzOsZXCi9SqCK40U9XItteTzSaXm8Vcz/SyBC8k6T++KAGLppJjhwuRzucts1X9QC9eo6GIBFvnF6Ig==,iv:T739EZGifNZSq/Ngqs7MMWXAuSheqLWSH0qfUhvpbHA=,tag:nNTYLWGRJhkwuKEuWh5zlQ==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0d0tZWFkyUXRHM3k5N1M1
            eURKYnNXdThOcFN3dFRjZ09NTFBCa0ZWL1hZClhTalVzTHdFUU95UDA2dThPVzY0
            MGVVTW5pWG1ybmRLaGYxYzVGZGkvSTQKLS0tIG51clo4cG1kbUR4ZUNkWUQzWi9C
            MmRDZEYrdjl4cVhRMjlyVExBb2ZxMTgKFG4om3L3rlaGp8GhTbJBBfMYbrp6+rTV
            Ydz88UpD0GhZoONDMooLY/2tmil/BeAzKDJ4jQimaHm6ikeH8e0mpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:28:46Z"
    mac: ENC[AES256_GCM,data:XpdgpnJtn9QQrX8IZHUiiMX8lxAii4d0OrxITAAz3IrBtEHR/EXxGd22lDTOATUAJnm8m55kSx1tnRXzX0JgmRf+2Or8XTbi8n3IGpoimqr41Sio5CQhdrkZV+e85PVe0FMg4XgbRLRrEwKnVmHF0aT+PQLykgrfv0sFksIcKuE=,iv:IPDtDDFdQliGraCWnSTwqvt+yMJ9ouFC624raonV24A=,tag:T8j9jZEsNsaZqRmbpwsZ0Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
