# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.config.k8s.io/kustomization_v1beta1.json
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./minio-ui.service.yaml
  - ./minio-service.service.yaml
  - ./pve.service.yaml
  - ./minio-service.endpoints.yaml
