# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/endpoints.json
---
apiVersion: v1
kind: Endpoints
metadata:
  name: minio-service
  namespace: networking
subsets:
  - addresses:
      - ip: 192.168.1.241
    ports:
      - port: 9768
