# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: openid-secret
    namespace: arangodb
type: Opaque
data:
    config: ENC[AES256_GCM,data:kAlqr0FMkm9aiq3puFfGbLIYwIYZwcht3nt0IrLwTamwOH/KuVs7YqCp05RTwQghhsI0McZhW5w3jlGtVu+pm8qPp2QJFDLSaPyu/2jCcjLj3TVSGTx6JP5UuHI112F6JfhQ1OsxQxbRhzJrnakWaP2UXMyfr1+QHZe8sS2jhcHHwYmXHCmX/R1KRBHn/ltXPvRtBLxTQn0qny1aRTEqbLohNM1KcpGMLNhDv0LfEei/yhmIeuG1rjD304Z9OWIjiXdz/KvDBgAruiqDlbuKJY8aSceLVY34I0sN1QswckvQktx0NvCD9/TZPrkcDXL877pzxH0kXa1igz8Lw/iJHIlj07yJvox/ly1ajN6MuvdZvvdP3gGd4M6GnjGPP/3K24WTIWhIlyjhGrEa9ZNcNNnNl+8IPn5IO8y0gi4D1Qm3yXWwKpGcpDUzoQ71dT8W9tdIoKIpuJJ3W786cC8Uu9sj0v14jm/V3ak0pSeWtz5APOS6DgqaFgZGkteYKg7kGZpHAjr9I3g+UBHg3dyzl/4Fb2qwVd3gyhhMj4Rku5kgmdDd80YDkXZsmiT5psHCIM6YvA==,iv:/+lsrv0Qgg3I66a2VfMBhawwhTarP/64f000kEii+Dc=,tag:Tmypw3eBCgTxRmpdkWnPyg==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaT045ZjdXcndMbkc4RVov
            Q00yVFFtWUs3Yy84NWMwcXNtR2lqY0VlekZBCktuS21ISXUvMTJqRFpyYnFON1dI
            U0g5NlNpTjdJV09mL0c1VlhPUEtFSk0KLS0tIG5LeUN2SldrdHJjS1pac3VKOVJB
            VjNSOWRTRWJyb256RVExTHRJSVNlM1UK0+UxgorNcCIIanyjXd5upwmvkZFB+aSR
            eaitRX0J5nUgvnCpa1vtBxUnw5HXznesFjxCcL6PAzqjhXv4CAgd6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:55:24Z"
    mac: ENC[AES256_GCM,data:DGmnyvUU6ZDVZljWvxvjYB3yuu3jbZNfOKBqTym9emwDgzVBp5pwP+updIS62NrySTnbhTi3LGVdd0rpPvEK+IgwQK0uP7TkfKBkh7QI+KVljuLZeiwCYKCFCPY9SXgOHyKOi2pElP9gu1bLror1NkEOS7KT0FzkdhCYqUFwvhw=,iv:uMABJLgAEZ88ypjkhXYRKFGmhooFJMpAXTnjONZQW2s=,tag:MwmqTVSoBYwueK3AQc/aSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
