# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: ipmi-credentials-shared
    namespace: medik8s-system
type: Opaque
stringData:
    --username: ENC[AES256_GCM,data:G8OnGyc=,iv:bDqDI2AQP2ufn1CzJZ2MXpq2RhQySCJVNA8q4b/GjDo=,tag:H3vz+PEAWfuGoxVVpfHwIA==,type:str]
    --password: ENC[AES256_GCM,data:PVaxJUg=,iv:m7QgiHQcfqBps58GKgT9EFuZx27+cAFEjQYxzmEBRHc=,tag:846bbFHMS1/x8oeYz8SHIA==,type:str]
    --ip: ENC[AES256_GCM,data:Wh5SjMNaPXCHM/hT5g==,iv:Vak6p5A9FK8FbiMjLdMDiOdPLzAkRk6jIL0w9uIj0jE=,tag:gGKUcqaYzOU8wQX24AAXvg==,type:str]
    --lanplus: ""
    --action: ENC[AES256_GCM,data:94yhQSuN,iv:8EmgDTHiQ/fkeUNw5PYuUoyYPwkoh4qG7f6bGfbfEDQ=,tag:eOXbV7cdgDrg0BqhdP724Q==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3ODYxK1dQN1pIMEdhbmZ6
            V3RaL1hBdWVJMkZXaTRvOUg1RmprcFNlN2lZCnFsdmFvcEV1Z3JReEdGdDlPMEEv
            dUYyMGp2R2IrcThYN3Q5MGdJQ3NKZ0UKLS0tIC9EZHRvRkdhVTRpbVE4bWdlclpT
            MXUwcGF5TmN6ZzFGMEtFNk94bUxnZjAKCHfs/58TLORzQLUTV7t6SZmUuu8cko9+
            uK1Y+0xX3BMLPuqIbomAdzymnzTp9F35dwvEBdsE+TwSfhKkfXO8WA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T05:31:57Z"
    mac: ENC[AES256_GCM,data:D12jTbsScb0gAPoVwN6x4uw5FClNqHrQ48+ULGmEdhcsL05fgZQ9crNdDBCeROtFtZNVjfAcZVempDpXsOO/db0Db9CrGY91AZXtYMUciJCfp3hVIho1RSI2jOeAPmhT6y+0kKPLW901/t3faHnxmGiLuEe5rFggNYPR/6jjB+o=,iv:HSW/4Dq/RdTDniYDQQ0WaI4lQ1rkSwdQjp6V/e08v80=,tag:mS1nb3mRR2/7UhgKaxRjJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
