# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: ipmi-credentials-shared
    namespace: medik8s-system
type: Opaque
stringData:
    ipmi-username: ENC[AES256_GCM,data:2N5DL8s=,iv:LcuEA8Ze+4UJ3o3UAXXyqqXeD3xZ4pOUz1blvtbSFx0=,tag:gadYB67uXcaSBerV0t9t1g==,type:str]
    ipmi-password: ENC[AES256_GCM,data:+mZkkto=,iv:iPWL6PJzwKgS/Ahe58DEDmVvL4s8pQt1iEPHunJ0Buw=,tag:4oSE+6Sl7mq/oYSSv0d8zQ==,type:str]
    ipmi-host: ENC[AES256_GCM,data:HTtvUGKlCkyxQgFVOA==,iv:y+CLHBGVANXDgcQP8LRgoO1ynXMnXhxlVcxldml1Q6M=,tag:ue6EvdiMdMtZ35HgUuz+Gw==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RmFNYi9yL3EyQ1BCR3VF
            SzhMK0pLclhaWXdVdlNVbm5WNk9QL2VlSVNZClVSanMxYkNsdjBZVXU5WU5VQStW
            RmtxTmFBTEJHSWpEb1ZVd0tORVh3ZDgKLS0tIGcrK0xsWC9aelVZL25FT1plb1lr
            UlZRdVNON1dvOG9oMEErYnpjMlV4am8K7MFTXKKUOqGdhjBNUAG471/Z/2m1qXVG
            H17/OAUopMA3i/gQJeO1tI65vPW/s5khXNRjXRWUJXQPM6G7T76jtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T15:12:30Z"
    mac: ENC[AES256_GCM,data:zvTvqxAlDzvh4f1u5ds6VdDmW+UveEoWSWqDslol04iwrx2zG8NnIqMYmz7WkYc1w6OIOdKitSTIRc7l1FzYNRLkJnPSCZcaVBZPZxmrfnzxI5CHY7S/ARndQrik19ad/rD285lq9Gpr+KRo3Mb1sHEMHlonR26ZvH++uVae98I=,iv:KsvKf30ccWI39VQOUIFtmfuBBBeAQnsQDdNj+ZQ7mK4=,tag:I9PDoRw3UgYi9GoXwyYy3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
