---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: ipmi-credentials-shared
    namespace: medik8s-system
type: Opaque
stringData:
    ipaddr: "192.168.1.232"
    login: "ADMIN"
    passwd: "ADMIN"
    lanplus: "true"
