# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.config.k8s.io/kustomization_v1beta1.json
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: medik8s-system
resources:
  # NodeHealthCheck configurations for different node types
  - ./nodehealthcheck-proxmox.yaml
  - ./nodehealthcheck-baremetal.yaml
  - ./nodehealthcheck-unraid.yaml
  # SelfNodeRemediation templates
  - ./selfnoderemediation-proxmox.yaml
  - ./selfnoderemediation-baremetal.yaml
  - ./selfnoderemediation-unraid.yaml
  # FenceAgentsRemediation templates
  - ./fenceagentsremediation-ipmilan.yaml
  - ./fenceagentsremediation-proxmox.yaml
  # Secrets
  - ./ipmi-credentials-shared.sops.yaml
  - ./proxmox-fence-credentials.sops.yaml
