# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: proxmox-fence-credentials
    namespace: medik8s-system
type: Opaque
stringData:
    api-password: ENC[AES256_GCM,data:F3V3lzS8bQHEQhoGkFuyZPLIAOs5OTcohqI0Z1Kih9LerEi2fBUpaCUxqNMvQM+zVDCYpfE=,iv:n0Fd9T2YBKb8bZJHrZw1xWb0WyKO8NJmSiNmqo8NSpk=,tag:r0mJCyZFFo7uxCjpaMeXag==,type:str]
    ipmi-host: ENC[AES256_GCM,data:DOiUWqcVmO20G9idsw==,iv:NDQqDQumpKw/znONRyqE7u/b1LRmIOgywsgG/LIXPXU=,tag:zAJSWATYbvDjKHUNe1dhEw==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqN25LcGxnK0hxZlJvVTMz
            Rk9KSVhGL1NXMjlBTUFrRmh2aDIyTDNPclRjCkIrc2pJWFBZcGhadGVIYW1RZEl1
            UW52QlZSM0xwa09GYUZtbm80VlRmWlkKLS0tIDlxU01BcWZTdmpCRzZpcHZCUEFF
            b3pNbUg4T0NMYUxvVVV0UmRocEVrU0EKObA5zXPAWOJ1UfJDAlFtMKLoO2uJUx6e
            0bk9S+sbHCDQ+RJufbIDJ+DLvznl/d7jkb8gD8hfzMAtdmze6V4cyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T15:17:11Z"
    mac: ENC[AES256_GCM,data:Ak3vO3057ceO8pDG6XmnkM+rAL+f26XAEpAGQFkkm5Chub2tRU6ZPpY5Ea5Cc4Oa4mGblu0AxRiSxzwL1VZKfDL9bylakk9HJqjMTzQ+744/3mKi217vveUXafPqJ+4VbuY3B5wUHu+FBsOoYHnJj8iDFxucottDE5v3mJ4JF1Y=,iv:JnrpCh/7p0ZBv+jaS90eMqHTI62/+S1l9IyfdJ/g5PI=,tag:d0C2KfyQOLOTjUA8ZhBz5g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
