# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: proxmox-fence-credentials
    namespace: medik8s-system
type: Opaque
stringData:
    api-password: root@pam!medik8s=83103bdb-05bb-42fa-9e28-487c8abd425f
    ipmi-host: 192.168.1.240
