---
apiVersion: self-node-remediation.medik8s.io/v1alpha1
kind: SelfNodeRemediationTemplate
metadata:
  name: selfnoderemediationtemplate-unraid
  namespace: medik8s-system
spec:
  template:
    spec:
      remediationStrategy: Automatic
