# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.config.k8s.io/kustomization_v1beta1.json
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cilium/ks.yaml
  # - ./coredns/ks.yaml
  - ./metrics-server/ks.yaml
  - ./node-watchdog/ks.yaml
  # - ./nvme-labeler/ks.yaml
  - ./reloader/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./csi-driver-nfs/ks.yaml
  - ./spegel/ks.yaml
---
