---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.config.k8s.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# resources: []  # No valid resources for ambient-config; ambient mode enabled by charts
labels:
  - pairs:
      app.kubernetes.io/component: ambient-config
      app.kubernetes.io/managed-by: flux
    includeSelectors: true