---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/image.toolkit.fluxcd.io/imagerepository_v1beta2.json
# ImageRepository for open-webui
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: open-webui
  namespace: flux-system
spec:
  image: ghcr.io/open-webui/open-webui
  interval: 10m
  exclusionList:
    - "^.*\\.sig$"  # Exclude signature tags
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/image.toolkit.fluxcd.io/imagerepository_v1beta2.json
# ImageRepository for open-webui-pipelines
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: open-webui-pipelines
  namespace: flux-system
spec:
  image: ghcr.io/open-webui/pipelines
  interval: 10m
  exclusionList:
    - "^.*\\.sig$"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/image.toolkit.fluxcd.io/imagerepository_v1beta2.json
# ImageRepository for immich-server
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: immich-server
  namespace: flux-system
spec:
  image: ghcr.io/immich-app/immich-server
  interval: 10m
  exclusionList:
    - "^.*\\.sig$"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/image.toolkit.fluxcd.io/imagerepository_v1beta2.json
# ImageRepository for immich-machine-learning
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: immich-machine-learning
  namespace: flux-system
spec:
  image: ghcr.io/immich-app/immich-machine-learning
  interval: 10m
  exclusionList:
    - "^.*\\.sig$"
