# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flink-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://downloads.apache.org/flink/flink-kubernetes-operator-1.10.0/
