# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.config.k8s.io/kustomization_v1beta1.json
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./agones-charts.yaml
  - ./apicurio.yaml
  - ./actions-runner-controller-charts.yaml
  - ./flagger.yaml
  - ./airflow-charts.yaml
  - ./ananace-charts.yaml
  - ./arroyo-charts.yaml
  - ./authentik.yaml
  - ./backstage-charts.yaml
  - ./backube.yaml
  - ./ceph-charts.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./coredns.yaml
  - ./csi-driver-nfs.yaml
  - ./dbman-charts.yaml
  - ./democratic-csi.yaml
  - ./elastic.yaml
  - ./external-dns.yaml
  - ./fairwinds.yaml
  - ./flink-charts.yaml
  - ./fluxcd-community.yaml
  - ./grafana.yaml
  - ./hajimari.yaml
  - ./harbor-charts.yaml
  - ./hyperswitch-charts.yaml
  - ./immich.yaml
  - ./influx-data.yaml
  - ./infracloudio.yaml
  - ./ingress-nginx.yaml
  - ./istio.yaml
  - ./jaeger.yaml
  - ./jetstack.yaml
  - ./k8s-at-home.yaml
  - ./k8s-gateway.yaml
  - ./kafka-ui.yaml
  - ./kedacore.yaml
  - ./kestra-charts.yaml
  - ./kiali.yaml
  - ./kubernetes-dashboard.yaml
  - ./kyverno.yaml
  - ./metrics-server.yaml
  - ./nfs-subdir-external-provisioner.yaml
  - ./open-telemetry.yaml
  - ./openebs-charts.yaml
  - ./piraeus.yaml
  - ./redpanda-charts.yaml
  - ./rook-ceph.yaml
  - ./sail-operator.yaml
  - ./sealed-secrets.yaml
  - ./stakater.yaml
  - ./strimzi.yaml
  - ./tailscale-charts.yaml
  - ./velero.yaml
  - ./vmware-tanzu.yaml
