# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: sail-operator
  namespace: flux-system
spec:
  interval: 5m
  url: https://istio-ecosystem.github.io/sail-operator