# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
    namespace: default
type: Opaque
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:YA+kD/mej+JXuWKiXKRjD4zbPalHi8KARVgFCw==,iv:yihHlhZ89gaalGnANVpYT7nnDpTf60X8ESbfAYWHkjE=,tag:T8bagAw6sRQMkdA/NfQrVg==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiYlRDYm94OEdpYWtOb3JF
            ays0dm11Z2hvb1JtbFNtRE9EckRSeVlxdFRzCjlrNy9QMUlPKy9NTVhFNEtpL2FM
            Yi8xQ0ltVWhTODc0QitSdHZsa0hiWUEKLS0tIGVxV1ZJQXpEb3dMS0lJSVZ0enov
            Y25UVDM3OUFMYVNMRjJIdGlUZ2hKRTAKyQBrEP/e+eH2RsH+KlVq8HP0Ph4Dai0e
            TTxMfBJIA+4clYkbikINOhQmjKYZkS1YnZoa8goSfySVk3Wzhu90Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:28:47Z"
    mac: ENC[AES256_GCM,data:k5I0JNNA2wIytn6W2BqeKk7vx0t2wHTbnDgQ2Kg3HVs9aiXt3jnIRB1NBM1pln2tRO8DJEfOAXiw3KSKkp1GfsFA/F4QTr+5cfRX8fo6gq9mvVRkzbMLIEhstpcWp7DUZDvgoNPJcpv3fxJL5eq3dIMt9QWC5AQgzmEUBZePHZw=,iv:CHIf/QE/af2Gar0OZ7XqXFRAKqPNjPHuiy7ynzi8dvg=,tag:aob65OOnUEmy5yoTF3liQQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
