---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/master-standalone-strict/_definitions.json
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: ceph-objectstore-admin
  namespace: rook-ceph
  labels:
    app.kubernetes.io/name: ceph-objectstore-admin
    app.kubernetes.io/instance: ceph-objectstore
    app.kubernetes.io/component: object-storage
spec:
  store: ceph-objectstore
  displayName: "Ceph Object Store Admin"
