---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/master-standalone-strict/_definitions.json
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: ceph-objectstore-user
  namespace: rook-ceph
  labels:
    app.kubernetes.io/name: ceph-objectstore-user
    app.kubernetes.io/instance: ceph-objectstore
    app.kubernetes.io/component: object-storage
spec:
  store: ceph-objectstore
  displayName: "Ceph Object Store User"
  quotas:
    maxBuckets: 1000
    maxSize: 1Ti
    maxObjects: 1000000
