# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: grafana-oauth-secret
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:LJ95UgUD6s9jhTdrBAoGR6MSEIFW2N9Pyfn7Fmd1t3544wDCeLeEdG1VVgACmzt2pEHv/6m053P6npqujR60CoYQn20alulHFKw+3BeilKq5+DTR9AgxwKCE4/EiycSBW6p6Xz1wu0Nf5PuJUOfB5R5zyD4s0Niq7/QpLK2RSSY=,iv:+kb/lpsdPiLCuujpohrYpsjMUTds6YsFUbp0506Npx8=,tag:Agr6uGYAV2Sft5UctKyasQ==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:FAZehhRZDQ==,iv:ccKTAsHSjPR1RdRwFQO1LZc10MTN9bdDAhS7SCZ8VIU=,tag:DtxZrSoDPUhrvQ3P4b6dpg==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVUh0NjNiZGhDdWEwRWc1
            eXBvclR5d3BCU2ZEcnI4NG5yMG0zbnUwRVhrCjBtMllaUEVST2dObVNTSjBnQThs
            dGZqak5JenBmZzh2bHZ1SXZlcWp2L0UKLS0tIFRMMHM1Y1ZQL0gxVXR1bERCMlBs
            cEM3N2tiR3ZNU2dmVmFxclJhV1hGaXcKJxwwjXl2OLQCJ+2lI+VqvAFxTT/oD1FE
            GouO3Ygg3qqwshTVdhULapvQeQhzN9TrJDi650O0DX5EMMY9DT4wWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:28:46Z"
    mac: ENC[AES256_GCM,data:/sw502QaN4iZaNeN4sZIKsf2EkTSA1zdzEKzLbjRtFGNsXYprMIiBJP229PJ82sDAMNe8nairF/UW6BBthB/cWTU9dxYbsFQOUpUb8iBhJCWyaI6M2UFr/lKYrbId6zYJK0FSBh5W4S6JJ+dfz/+3vSmOH+np08tehO2fV/rKGY=,iv:uOc4+dU69AAqlnHCHfZBxmU7QK/kcyW9Bem7MgNBx0U=,tag:qnoUFsWFYFcPMikZetUYIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
