# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: oidc-auth
    namespace: flux-system
stringData:
    clientID: ENC[AES256_GCM,data:qNhqYn75o6Da2L1Y0NadbmO6y2W+DQBNb1VDgp4aw4kwji+pOnSooA==,iv:wFmeY5dnc7LZ8KVIOvhzN5xxlmIvsyTTmhgwLjL0XBY=,tag:MmNxL0Q0FUWKNp4/R+dvEw==,type:str]
    clientSecret: ENC[AES256_GCM,data:rEcVLWe5wnoym9ttqxKpysmSJiUHK0rY8gqAkxKnHGQRgH1NCB24j7pe1kJUxNAzOoPOE6hKzPy0HoEtUl5SOP+HZZQvujdiUR/kIKR4Y7vIz5GygLXduqxNXqiaWZjhLFNqJGo39Xhbx9zQ7yfDfiiqt6MXFBR5rRWzURNJxhk=,iv:Xe4oWGfNIPDuEZt1jZPtXGyQESxgk/Kl+tqAjS1X+Qo=,tag:c3ILvh8EeqjyrOH71sua5A==,type:str]
    issuerURL: ENC[AES256_GCM,data:fzgbmE5CmiLOUYUmTQgi2+8SkkMZXjCbk20gp5JWRrmW2Bgnk5n5EcbER47pjC7fUQgjfsFOGCGzU46Qqg==,iv:unHlwtke6Q09Osa366sNgsh5AYoeM6+3CZJTkdQC4vc=,tag:Fq1PIO5v6nmbb3wdIKEdLg==,type:str]
    redirectURL: ENC[AES256_GCM,data:hM9/8X4+UpAZh27nSDP7wqY3lXKumzAWHsca3whOns/SpXVoREd+eKVzpPVvtgQ1jvrC,iv:kA4yQJFrBeEx5jqlwSXZHaytzau5mfs431FV/Gb1hN0=,tag:ZT20L72SWiXg3IyhDmiEww==,type:str]
    customScopes: ENC[AES256_GCM,data:gwGDWD46/C0kkdhP,iv:XdbRXJihdYm3f364FKlH6ePtTIE7JiMn/cSTjMvghak=,tag:Z7Xdhrf/EAVapXooyYzq8w==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRWlWQkRpQzkzMitCT29O
            SStMNHh3a0h2OUdKNFdTNEdDZDl1eW5hZkh3CmNPSnVtTEdqdGtFckk2dzFHYzhn
            b0VPN05aRG9nbVQzdXhzK1pJdmVVSW8KLS0tIFNjSDY3UGN1UEJxQVAvNngyNjVt
            bUt0QWIrcjN0MHQxWVlFMDcxWmJyWVEKYKhIbQDSAJmVofSsHCCqwZn0T1UUqgY9
            uK2HBOG6m8EVuaIYwRAyyJU5gvgzYKyul0knhuhcEfJkmJh5AXsEeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:28:46Z"
    mac: ENC[AES256_GCM,data:nSA3qSVe5ePx9fVZfRPg9b9nChnkTyHHaKHenwpoQrklwYypRr173GPq+lhian0wmYiPOgyUr+isVZfCmjtUtngGQQHvocnj3HMQ2S3U4fSNdWrKbTzM1geIPD+VO4wJyoRtMNG9omY9eFpL843CamKmbBlxNOyrYaPcSIPnpSk=,iv:vXQg3flLe2ByBqHW+XNGP7RGMdh9z0xcSa1OItkaFZo=,tag:6yWHXzPuZ8qVbeiQ7Hei/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
