# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: oidc-auth
    namespace: flux-system
stringData:
    clientID: ENC[AES256_GCM,data:pnXoORqpCUeUr/hli6rOnhfDQX1Q0KicaGKkB/VCeR+9AeYJtNZvyg==,iv:yrdwiLej6zu0wxXYxkXHSbKleZ1OkvuEvkfXyiWgIaw=,tag:oPbINCfyoqrbUJPix4CaMA==,type:str]
    clientSecret: ENC[AES256_GCM,data:0x1a9vxJF2MpubktjsqHMzUd/crC/+JaokZZahS897DJyP/j77EN+hQkKSGEAHAU1v2RhXIsz6n5NN4F70otaI5BATKFT3j1dSjKZvqjtVNakTisSwjJ6CVOzcaR1crPVoLwqpzN2tqvnz7QeOqNyYrxMPJzSiaxStwLHj7QABE=,iv:sVPACRldT9VS+/bQUEl0rt+q7jQOVL1b1aeEjtHUExQ=,tag:xsc9ys2tzCuQ6ltHfunQag==,type:str]
    issuerURL: ENC[AES256_GCM,data:FLw3UCKCShBWnqZ/FHtOXwI0d3LsAGl30lf+Thcic0E9SVIduDB3ctboD51ogiZ7tlnJF22WTPtWmYlvoCkoh65gU2Crt9OmCOwgvldq8A==,iv:D0EwQEm2aZ3ni5/CvdfMvPKtXEz+i5NLGG9SVQphdXU=,tag:E+uJbengxFZMfGs1GtdWNQ==,type:str]
    redirectURL: ENC[AES256_GCM,data:U0DVJzzy9n5vk28gLBARQ1Z6LLOWpLT/+oHB/vUgkeQbG97df9Xc1yxxLphOVR2A+tYp,iv:mJN3cdpR7VH9SboDNTGmRFXmuSDRH3kGhlcUGiQMMes=,tag:RXxQWkaIf3tpULeMqm5crQ==,type:str]
    customScopes: ENC[AES256_GCM,data:WFRRDuH0wfhzJB0t,iv:MPyio/oxf5tlA0+zf8Tg1oF3r+tAi2cE0lT+h2C7IN4=,tag:eQbBI9l7254mDOyRMvUKfQ==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqY3QxUEV3YWhVNjhvMkpj
            WFk1NzJJT002ZjdDS0IyOWNLZTlEdjU0MTIwClNKaDB4SHZMeEZPMGJSazU0cnRQ
            VTFaU21Za0Z2cElCZWVibFpBV0Q3cDQKLS0tIDFxN3ZjcjduWGlOVXNCRWhZNnVv
            emw4V3NudEhITjdmem1peHkrZkt6K0EKdCP55BbzGqd9PTWzW+tgFFM37/yvD0iG
            s/CWChxUADX9YGyscLjJrGSQzlZTIEHefS4ZGjV8oAJSGmlidF1YEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T01:49:07Z"
    mac: ENC[AES256_GCM,data:zyD7MkGZ+3sydKJCQ7VKPSL6iqLyS4GCTVSxWjP2GqdKYtpT7MbOYbSu2GgSOQPsEPULcFGQo1bq6LO3ILK1nwDhwzhNcmGRFYwG/csmx/8V/Wr4Oidk0GnO25BRcwrjmr6p0U1DCZNfRJelJ3Dy5/s9tDthsJ1aizpX/wqecB0=,iv:F0cExK4DWKkIXHUnFmtQEwTif4pDkr8kc8UnctqRPRw=,tag:OlcTAgsrMH3aULAnVtJWUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
