---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/registry.apicur.io/apicurioregistry3_v1.json
apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry3
metadata:
  name: apicurio-registry
  namespace: schema-registry
spec:
  app:
    storage:
      type: kafkasql
      kafkasql:
        bootstrapServers: redpanda-cluster.redpanda.svc.cluster.local:9092
    replicas: 1
  ui:
    enabled: true
    env:
      - name: REGISTRY_API_URL
        value: https://registry.${SECRET_DOMAIN}/apis/registry/v3
