# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/networking.istio.io/virtualservice_v1.json
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: apicurio-registry
  namespace: schema-registry
spec:
  hosts:
    - registry.${SECRET_DOMAIN}
  gateways:
    - istio-ingress/external-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: apicurio-registry-ui-service.schema-registry.svc.cluster.local
            port:
              number: 8080
