# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app kellnr
spec:
  maxHistory: 2
  interval: 30m
  chart:
    spec:
      chart: kellnr
      version: 5.0.1 # datasource=helm depName=kellnr repository=https://kellnr.github.io/helm
      sourceRef:
        kind: HelmRepository
        name: kellnr
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    secret:
      enabled: true
      useExisting: true
      name: kellnr-admin-secret
    kellnr:
      origin:
        hostname: crates.${SECRET_DOMAIN}
        port: 443
        protocol: https
      registry:
        maxCrateSize: 50
      docs:
        enabled: true
        maxSize: 100
      proxy:
        enabled: true
    pvc:
      enabled: true
      name: kellnr
      storageClassName: csi-nfs
      storage: 50Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 1Gi
    ingress:
      enabled: true
      className: istio
      annotations:
        kubernetes.io/tls-acme: "true"
        cert-manager.io/cluster-issuer: letsencrypt-production
        external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        external-dns/is-public: "true"
      tls:
        secretName: kellnr-tls
