# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: kellnr-admin-secret
    namespace: kellnr
type: Opaque
stringData:
    KELLNR_SETUP__ADMIN_PWD: ENC[AES256_GCM,data:buJA3ZV7vp9X/TP4vpeK/VigsOhF1BA=,iv:CzwVEfBstCdHlZSGm5BBLiSh6dlW9blAzIxpklkyOvo=,tag:uZrgGLVq1901KBfhhEuekQ==,type:str]
    KELLNR_SETUP__ADMIN_TOKEN: ENC[AES256_GCM,data:8+zvALLaRHx9gDtNHVD0rzAjbprRLqy1O4AfaoA+dN/c,iv:iL0E9p3zYvIBuXQQSbE5SZykb57gfumrf5R3n1T9/Tk=,tag:ZDZ6u3Bua8mtUPOXXZ+EdA==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTlArUlNHMFpVSmY4bzV1
            d0pOcU1xc0pGVUtTSDRpK2NBK1NtUis4K1NVCjREWDJCZUZ3bUdPR3N3RkRNbnVJ
            cFIxT3FGVDJiOVBDNU9hVUs0bW94MEkKLS0tIG1GMVRDZlY0VVFTU0VjNGtXeEFF
            Ti9LdnkyU3IzMXlVb25BRHlmNURtODgKAlkFKoEWVNFpzRU4QsQ2L2vAed5e2TVM
            u0YkmJHQ+yMcZBlZqB1kr2Uz52KOVeue2ZXEkHxMey/vqZpdCc7HrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T06:43:09Z"
    mac: ENC[AES256_GCM,data:Iz2ROoSSbEZhLWhQxsjd5jBOuQJcKi1DHxnr/iom5Jrj/84VUNUgesRMK8trCKshIA7lQ7ZFM012NrdBhETe+JstmEILdsC9KLUz1X+ijR9ehOwfoJs3+b7xN4nrOGvTXIKi9UribYHTWJfWHh2KihR/ISjuu333uiW4Xiq/Eqw=,iv:hv6p/QBAKtUDasTlHfMKL3wWtMLaD0K7bqIwq40Jru4=,tag:im97I5LwEB2vFbAc8MBdGw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
