# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
# PLACEHOLDER - Run 'task sops:encrypt' to encrypt this file
apiVersion: v1
kind: Secret
metadata:
    name: kellnr-admin-secret
    namespace: kellnr
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:AAtzzk7ZOsLLC0Q48SdOt2HxBkqDJCQ=,iv:S76yyks1+1aksOZ+7tVdRedHsfaiNvUj6Oit+Tqoie0=,tag:Es4+SiO6pEzoDqSuix9PBg==,type:str]
    adminToken: ENC[AES256_GCM,data:X7XybyPwFLsWT6aU3Rikms/hIa4+W3YXR5EJMEn8A7qO,iv:5poeusnw5kWVVwg/KTEagBN4MPzcKanmCVDfT+MPioU=,tag:uf3axfad9VC3V783XlVLXw==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4Rzl0dWJFU1hhVDJaY3o0
            bGJ2bk9QZnl5UkZYUlYrSWNaM3lvZmFGR3pjCkhNTWVQd2hnSEJmaUhNVnF5MXVo
            NDRhK2Rsb0RCK0FOdGowUWxsK1JESTgKLS0tIFRuRm9UeWtjV25ha2JxdmZkMFVi
            Q2h1TWVsRkw1eEcvM2xUL1dUZzJGTWsKZRTv89hMUHxXyzIoJKBt9da7CVTMzOO+
            Yl4cqVWa7zU8iuYdyzokGr6XUYk3KsUUIotBRb4kboiD3MSfnkX2ZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T02:48:21Z"
    mac: ENC[AES256_GCM,data:zDaalT3rJvCFYB75dxjVdBrXPWLFkq7hSQlpGEUvr3KNY1wVitkWuJWKF2mdWTsDVp5k2tNGG88xqp7xfbGVFy3zjfQSuAoOWA+I4WaTofKfGyKFrwGSBTM1xs5nrtPw1LhJY1d51geI7eU9niqfap2rlUOtFBG6LjS0cf18wyc=,iv:4vWzX95vpR35YSaiguo0ELrB+LYBXGeBxWWRIdWA0+Y=,tag:HK0AZbTtgPpfnxwVvffRZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
