---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitnami-schema-registry.yaml
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./prometheus-community.yaml
  - ./spegel.yaml
  - ./weave-gitops.yaml
