# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: authentik-db-hunter
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:ZbsO9BWA,iv:KBkwmkQVZb1QOJeC6jGE3Ov+3PNry5sDgrUhsHcouHs=,tag:/7YXsJusKRPN3SiorQdyJw==,type:str]
    password: ENC[AES256_GCM,data:RdcWJv0zqAZOSYv6,iv:/STTGJpb9XtvqUAXsTEkZ3IhgCboF8uH6/c/4PxkxaY=,tag:hFaVwkMujcyUsVkM6mCJFg==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpM3RzM0ZGYWMrK2dGcCtO
            endldDVQeWozbFdSSXplY09DS0F5OThsL0I4CjRqY1duelV1SlFSd3llSXpyQVFL
            b3NHZlFoa2I5Z2NyS2dZRWV6QVdLQWsKLS0tIFdUMkxxNG95aHc0aFI5Z0pCSExl
            NVlDQUhZa1UvRlMrT1VwaXhqYkw0NUkKOHTwfBWsJw4mvfjal/pHFgUodhrkr+JO
            pZ88hPmg/5l3o/TPngUBeq9IdVlS2bTfrVg7mpvC0yIuQyaA9EBRrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:28:47Z"
    mac: ENC[AES256_GCM,data:tYSXovKXcwCo0mxo/Mwfo0ZuZQVKRpmHQf4e/GPlzbQMQEQN6BSFSBP3aaVFVQrF2zMEs06V+YzHMmzjBAuEY4vTVuK0umjkCXHTYfjWsvqYnq8acGZNFT6V3e+OhNFOtg2yYX5KOB9y12l+T2JorYJ5nLdSNHxztT5WRH1/I4s=,iv:qyigysr9l3si6xi4f4GHB9CPBy5K5KVDTDrcThTUClw=,tag:niJ7MbgCw05LTtv91sNC0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
