# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: postgres-superuser
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:JCHhONV0US/NCs2mz7VdfgYIOD3IbOT6kg==,iv:4W5/DIqraj4yUWjBqC5BJQJbbY7FZnMZD4Z0yKMzpY8=,tag:YChuw7P3OpA4FT4cTrZATA==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTUZDOFBrbFpRM0p1ck82
            ekx6ZUV4R0ZvMzg0KzE4dUs2VU5lQUIzVFVzCk5YN2RReFBvS1BpVSt3OW5YYnRq
            NDNDQ1FuNkVBTzlPU1FzdW5mTTBrbWcKLS0tIHoxN2Zia1lnS21zbkxWcmlJYzVl
            K1JyUHRza0plYmJlRUt6UVh5b3ZtdVUKBRwRDVU7Tao9iB3XH88esiuRdrgGTms7
            fLqhtcHvz5s6tHqSFi+C5baqD/zvD0nHSeaIvKbCrYJTAUBUFCabNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:28:47Z"
    mac: ENC[AES256_GCM,data:/vpzSj/OuXNMh06+YO0NhHpo3aZmAjWZ6BN+SOKWUwFNOpCN9ZUPtPmP5DCYPHpJAW7CY9IlLQVPN1TdnfuFmO6qiI3oJOxEXJ0zJA6owX2NW/4mBiuMIhwbGIeHuqqvPKOhhP5DYAtDrkmnC/10sWfvKOooMz3x+5nROmzf+1c=,iv:+Fwp2wUg4HG78K8o47N96fo0J2TrIemVjyvddKsfPQM=,tag:Cz77d8nQINLst6+mikOiww==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
