---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/networking.istio.io/virtualservice_v1.json
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: flink-operator
  namespace: flink
  annotations:
    external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
spec:
  hosts:
    - "*.flink.${SECRET_DOMAIN}"
  gateways:
    - istio-ingress/external-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: flink-kubernetes-operator.flink.svc.cluster.local
            port:
              number: 8080
