# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.config.k8s.io/kustomization_v1beta1.json
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cluster.yaml
  - ./object-store.yaml
  - ./gitea-db-user.sops.yaml
  - ./gitea-db-hunter.sops.yaml
  - ./pg-backup-secret.sops.yaml
  - ./postgres-superuser.sops.yaml
