# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: pg-backup-secret
    namespace: gitea
type: Opaque
stringData:
    aws-access-key-id: ENC[AES256_GCM,data:y4KQe6hjrd2WHZa8jHbDEXz2AaY=,iv:k+Tcdx86p4Eh3Y+ZTcLwmN4T2bWlKTJc5tUJdwsNGlo=,tag:h9H1lgCONeW3fVYLC0rX7g==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:wufPTSPiPjTTTRZIG2Sg+lJEC1f0KCqJgz5cO6TJHcCzHXvRzcaF2Q==,iv:ZVXHFlVb+BhuxoNvLSpBR+SBHgHBgXLcsTWJ9f/YihU=,tag:iS7sJCXB4PmA3b8zVrcQ8w==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISSs3dVZWOS84UWFoKzlL
            b2YxYUNmbEFJNUdVMnQzUFZXaWlyVWRJblRvCjFFTElON0g2VGt3VDFwRUFsVzBv
            eXI5MGRYRWlIczVNVXZBMnlTdmxFcncKLS0tIEtBQ1Z0ZWYvN1hneTh5ZThnYUlm
            SjZwYXRZZDlSQ25OajN5aUhaYWl3d0UKReRhOOowNc+3VM3i1jigG2JVS74pBGao
            7OfHn21h3sQS03CeJYu2+16Sp2AY9sl7dfvsz4hiU4ToCLpin2+80w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T14:38:09Z"
    mac: ENC[AES256_GCM,data:fmv0MhavtQ+ffQQ87BXwSucpDdbeMqTNf3v1I1iGhCNoPZFRE9R2K6leBVBB+SWEIFUQ9Q/38adGYry0ZSeeeRTsXS4ispeHbpJmO+35OP3R1d/JAOPxuFZnBCGSDIRRFrG5yaTk3zYZsnAGLLZw2I/IH1/y3C3gRBWWASqZGPE=,iv:3+1QQhw/uU8otjHJtsyprGsWKtzUOdmBcEzpgXrkUPs=,tag:2JxX0RLxPKUdDYgivOAi2g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
