---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/master-standalone-strict/_definitions.json
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno:secret-access
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/component: admission-controller
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "create", "update", "delete"]
---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/master-standalone-strict/_definitions.json
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno:secret-access
  labels:
    app.kubernetes.io/name: kyverno
    app.kubernetes.io/component: admission-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno:secret-access
subjects:
  - kind: ServiceAccount
    name: kyverno-admission-controller
    namespace: kyverno-system
  - kind: ServiceAccount
    name: kyverno-background-controller
    namespace: kyverno-system