# yaml-language-server: $schema=https://kubernetesjsonschema.dev/master-standalone-strict/_definitions.json
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: atuin-db
  namespace: atuin
spec:
  name: atuin
  owner: atuin
  cluster:
    name: atuin-db
