# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/scheduledbackup_v1.json
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: atuin-db-backup
  namespace: atuin
spec:
  cluster:
    name: atuin-db
  schedule: "@hourly"
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io

