# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/service.json
---
apiVersion: v1
kind: Service
metadata:
  name: &app atuin-postgres
  namespace: atuin
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
    tailscale.com/expose: "true"
    tailscale.com/hostname: atuin-postgres
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: atuin-db
    cnpg.io/instanceRole: primary
