# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: postgres-superuser
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:nm7eqIfEibzjmqGv3jvQDuA57quhI8sxTQ==,iv:EEOL9L563tsIuvBKACRADzhu9IBOc8nO/2GIrYKZXB8=,tag:nDH154DzjlQ0ovfaASrJ3Q==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVTAyUEtKQVhOK3NMZDZl
            dm9LWkxxMVNONDQ1TkpvODBPa2N4Q3BLNmg4Ck9UTkRxcjNmelMxa1I0VDhmK0d1
            c3VreFRKdENjV1lkRWlvcmVVSUc2SzAKLS0tIG5TVW52SDdXQ2NwVDM1VTRNT0ND
            OVhiWStuNEIrZ1Rwb2x1V210SFMyZ2cKl6p3N59Spp4NVtSya+23CZy3Bk+UhG/I
            GBwJFv2Bf1JFz9wtAHMPzN397pP9L/ZGj/Y7WJLxz80Ny1eB514+5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-20T02:21:42Z"
    mac: ENC[AES256_GCM,data:mHk6i6E3U2bM0o7yfqMoeE+kPUum1l/eFgtYnqg/SX4qZ1OJ2ukMvXsNffwAADFsASFQEXx0z7D65aCr3Iy6hf4DaIWWh6ifRwApxV32RZQuvLuZy/RXuLpvy0KC1pby+kY+7TJKgVdj3vKFKnhkh12+fPb554qo/90PwsJy4KY=,iv:bMCXMDHjUtzobAzglrrSOa1OEVMoj5zKvVd8Z028yhc=,tag:vyXw+N51vjeFwnjjjc3+tg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
