# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:ErwWbM48ehIXHOq/,iv:PprOu9BFi+GvSBNuasNqvPNwAhP6qOUJO+px/mwaI60=,tag:kz5GxAsjbDHZjA0navdPMg==,type:str]
    username: ENC[AES256_GCM,data:XXKr,iv:r5O9vACLrGC+fc06iAZ/M3wot8fquOMNwbMTyzODYdo=,tag:9PlkJ1wfuse1SxaLssOl+A==,type:str]
kind: Secret
metadata:
    name: postgres-app-user
    namespace: immich
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SUhyUXdQV3IyQnNxbEhr
            S1VHcFNlb0IzVnBJaVJpdDEvYXJGd0xMQzBvCktXaVVJbGhuVHZmbk9kelEwYzQ4
            M0NzdWN3dnZBb3Q5aWxPamU0WmlncTAKLS0tIEcwSVl4dXR1T3RCdk9OWVEyZFRF
            cU1pTTBwTG1aMjEvYS8zVk9Tb1c0aVUKLKK9T2IN86Zht7mo4IAtZOVnCw35zdWr
            cXMT/XMm9MPa+OAWt1wsBWx9bImw3xIRyFG+ScCp9FjK2gdq+36uSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:28:47Z"
    mac: ENC[AES256_GCM,data:WmnQXTFR3TNtp42nDWtEKltylyVXpvy2ZOdM1kW4MwGchemU07v9XliWZp8nuVmNt2GKKrLEfn025C3U++J7dwvI3ZMtLe6c4tq5i4t3Qy4EHfT2tkgfXDX6GjjjaktNwQ3RlEefeg8nVnBymMBHsapglStzKypzI9vihrzfdvA=,iv:teedoIeIcMS+BBqeIF5PPlVlak5OsG03S/YJKMhM6vI=,tag:nYpVBXjI2Rpcgo1gzCPd8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
