# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: immich
type: Opaque
stringData:
    aws-access-key-id: ENC[AES256_GCM,data:dyWPI8jq9jEUmPs4Ec0MYwJjS9w=,iv:03f5tJ7gG3wUBkeqN8vq/OBiBAVLvcZ52B7vfR7j96g=,tag:QZEYXl5WQmbQGxEKt+KK2w==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:d5vk07eOLLGOihSSP5w5WZ32dAmSYiaUy8XogQPj2oLne2kwi3LJ+g==,iv:v7oKU6Ii596KSuBpz6hMljmBp1JUevqjM6aCzJWeEcM=,tag:b5ibi5wsq+HURyOGYcHG/Q==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNY0lPZmhxdDFLemdBa3hi
            TDVRUzczVXBrM3BFbFB3VS9zR0V0Qyt6SFQ4ClZIWnBNUVVRZGhYd3R6WnBRUnVj
            ZkNYS0F2OGtMTGFLdmVlVmM3ZWQ5cGsKLS0tIDh3aENRZFlxUk1XcTRUUWZxV05R
            SzBCUy9KS1ZoRk5GTUxKMjRRSFZ2czAKLb6mWqV4MJPOZesBEQJUVHQAZdUhRj0c
            XBM7Ns+4YmtlsMjiZ2h6N+J1z1ynSoKNunoOpq6nQdIFHFDLMd1nZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:28:47Z"
    mac: ENC[AES256_GCM,data:Z0zdRRUodm6RHzI3tUsWWadelb6ARHr+YnJk4nxMYabr3InDtpngjlK2FKvT8HovLBfRdXsTDgZGYZ00rF0ngWFVg+aL8q13XbfJ2EWjXiyKkk0+Usz6pnwOrFc4tD7ytzuMMQkG913DW8DJDDG5eKwwFnfZsG2Pu368tuMp7gg=,iv:1VGBtMSUGL2xuBH4twgdGtg/6ufdNIQSbtikma2sQWw=,tag:OuLSuQTwXNeCtxkrIeT8+w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
