# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app gitea
  namespace: flux-system
spec:
  targetNamespace: gitea
  dependsOn:
    - name: gitea-db
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/gitea/gitea/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app-db gitea-db
  namespace: flux-system
spec:
  targetNamespace: gitea
  dependsOn:
    - name: cloudnative-pg
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app-db
  path: ./kubernetes/apps/gitea/gitea/db/
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
