---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/networking.istio.io/virtualservice_v1.json
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: tekton-opentofu-webhook
  namespace: tekton-pipelines
  annotations:
    external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
spec:
  hosts:
    - tekton-webhook.${SECRET_DOMAIN}
  gateways:
    - istio-ingress/external-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: el-opentofu-listener.tekton-pipelines.svc.cluster.local
            port:
              number: 8080
