# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app knative-eventing-extras
  namespace: flux-system
spec:
  targetNamespace: knative-eventing
  dependsOn:
    - name: knative-eventing
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/infra/knative-eventing/extras/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
