# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.config.k8s.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arangodb
resources:
  - https://github.com/arangodb/kube-arangodb/manifests/kustomize/crd?ref=1.3.4
  - https://github.com/arangodb/kube-arangodb/manifests/kustomize/deployment?ref=1.3.4
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: arango-deployment-operator
