apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arangodb
resources:
  - https://github.com/arangodb/kube-arangodb/manifests/kustomize/crd?ref=1.2.49
  - https://github.com/arangodb/kube-arangodb/manifests/kustomize/deployment?ref=1.2.49
