# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
# PLACEHOLDER - Run 'task sops:encrypt' to encrypt this file
apiVersion: v1
kind: Secret
metadata:
    name: gitea-admin-secret
    namespace: gitea
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:L25gbBXDq8dwgMY=,iv:/bxme4gsgy2hLJOB6AUwXyxPtBrCreh6jXMop2L++q4=,tag:a8KLRzlZ7za5V/Doe1z8bA==,type:str]
    password: ENC[AES256_GCM,data:HdIQ1JdR9iXQy2PsDRfyeZR0ItZPAE4B,iv:njrWp0NioAhAneO3rl/Ln83OWH7nh7v92pc0FPUsDDQ=,tag:yOfuC2w2lAS37dzA3r7b0Q==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNT1pHbWNBdmlCMTExQnlO
            dkRJMWNDbnV2SXRCY3VzWXVjS3JiemVnUEdJCnlweHBmek5tclNwc2dvU0h1TUFL
            aThMZWVIQWRNVnVyVUhnRnVKdFM3dEkKLS0tIDRQamc3UmhocWppYkZZOTEySXZs
            MFByYkdMMTB6K2RsemlEMmZrRWpZS1EK6VJj2CsFq8gBdi3AGkEX/DUpbFNE/UbV
            micJb6vyZwpUY+e38sET4eEvTw1ImVL9XfH0YbkGk1HFONxOAhp85w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T02:48:20Z"
    mac: ENC[AES256_GCM,data:BRGgjV59BuMFbKpEUciXWdVgMEXE4ogUYALgxvHgCdC4QXo2U14hjhyhK/dHR7czb1UlWMAKUJyQuBNmjFsYgN9e3fzZgHVujRNuHl0R4ED9AwmOFCzzr3rfQXfmmrWTPtXcOnhdRZeihF8byCUvWS84e2s+BXvoqTtTxRs0grI=,iv:QIHuz0J+NYXWelywi8myvgQxO56h7cGq7oS4IvZhDTA=,tag:Ll5ku/v30WuS3LnrfgleTg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
