---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-healthcheck-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-healthcheck-manager
subjects:
  - kind: ServiceAccount
    name: node-healthcheck-controller-manager
    namespace: medik8s-system
