# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.config.k8s.io/kustomization_v1beta1.json
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: medik8s-system
resources:
  - ./namespace.yaml
  - ./crds.yaml
  - ./certificate.yaml
  - ./serviceaccount.yaml
  - ./clusterrole.yaml
  - ./clusterrolebinding.yaml
  - ./deployment.yaml
