# yaml-language-server: $schema=https://kubernetesjsonschema.dev/master-standalone-strict/_definitions.json
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: home-system
spec:
  replicas: 3
  rabbitmq:
    additionalPlugins:
      - rabbitmq_mqtt
