---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fence-agents-remediation-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fence-agents-remediation-manager
subjects:
  - kind: ServiceAccount
    name: fence-agents-remediation-controller-manager
    namespace: medik8s-system
