# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.config.k8s.io/kustomization_v1beta1.json
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  [
    ./kafka-cluster.yaml,
    ./broker-lb.yaml,
    ./node-pool.yaml,
    ./metrics.yaml,
    ./service.yaml,
  ]
