---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secrets.sops.yaml
  - ./helmrelease.yaml
  - ./virtualservice.yaml
  # - ./ingress-forward-auth.yaml
  # - ./virtual-service.yaml
