# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
type: Opaque
data:
    SECRET_KEY: ENC[AES256_GCM,data:v9t5tm4iWBjau/6q4DTNwE6qRQEP0/Nj4QzvDwFcRMEHI85VIAO1UoOHqXXGeHoRjIDVuc3NvUTB0ysR+Ks/cQ==,iv:i1VWAVFzn4odDMG+bs2luiTvYPaJr3PGcn+GrW0nQHI=,tag:gxt4X9s73SwPx7ZYNXD5Zw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:8OpXeMIz18ovSdv4swrEa9qqXgmgh6er,iv:thPal1+JlpNFjeqMHN9Zo+kXt7+lfxit7S2lRE8chnQ=,tag:AjUu+53AJBXslhgLk+D1Og==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:kmU+sem8YNqhWiZj7dWk1cuXToY=,iv:547/8Xz8aqwhvyZl5uIssLobaRGnRDHzbMEubSvFVKM=,tag:p3PVeYzSYqTEGqtjs3vIkw==,type:str]
    POSTGRES_DATABASE_NAME: ENC[AES256_GCM,data:bhb3I9sBPFyQ1OPT,iv:aaXS/0xdEloGhbzlJaB6LOq9HKikhFzz1CV4VK9relg=,tag:+NVw5UYjgU7EKBxhYk1wAw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:Xdqur3fy5mb4EBwL,iv:0CticwoPIyBWQJqDOQ+ZQmUNmbGlWVAHgncopNjlaBg=,tag:E1kKFdn/jL8PUrfiL/j6lg==,type:str]
    EMAIL_USERNAME: ENC[AES256_GCM,data:8DMlPCfe1pDciVD5tSd6IIPQ5frcW4AAYKyrm0tLviPpFreHW2FCIjFDCfbyYeEGBtpe9A==,iv:mB62ciE7abhZ3TDZf502xV8vbH5aD3wEVd1je0XGCrE=,tag:upGYk2bZh13TWtIkwI5h0g==,type:str]
    EMAIL_PASSWORD: ENC[AES256_GCM,data:FqqJX9hyNqgBhNd3ezVW8AEbKIF2UcIslDkA4Q==,iv:IW7cqdK+03oi0DJQ3K5R54FNhhJTNNZ//liQxJlkmUs=,tag:q+3Wgup6UuKkOxD3v1WxGQ==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZXZ1TDJpb1NURm9CMVJN
            WXFHL1lzbjU4aklxYUQxd3JkbnNHRFVJdURVCnNGcDhFUU13Y3ZWd3Z3cTBoZUkz
            VjJ3T1lUakhEOWMrKzREU2RMWXl6dTQKLS0tIFNKc0J1MXBDTjBHSDhXUVIrNWdP
            VkNZeGt5Y0d6N0VoYkhUNENSQ2VMU00K9BBHu2bDyxlhfKdrupgsXH8vzjkipQFK
            GKxaK6AdYY+5+sm0ws0XKxxalo/Lx5vR2QFgql3QNnboOXqhCWf+/w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:28:47Z"
    mac: ENC[AES256_GCM,data:4ZqnHJsLjKuD4aTsmPiKL1QzfYhP/yQQzC6zp+kYDasVg44Pk1sGX7KbmWxcIqUo0XwFr8AJ91SKNdTC3MbWnBKc/14aLoV8fDe61W7MhdBg7CsxDuuKUcpHecMaMCMPRSGFNDcSgB8oaQ0787jRpmQa4O2sVt9jlIBtH6h8o84=,iv:U1zW+kLHvRSxoXgd4kvdAgG7Zx3ezr5YypHWTCqgxCY=,tag:Ha/Blgd1GqibIvOEGw1gMQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
