---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/networking.istio.io/virtualservice_v1.json
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: authentik-outpost
  namespace: authentik
  annotations:
    external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
spec:
  hosts:
    - outpost.${SECRET_DOMAIN}
  gateways:
    - istio-ingress/external-gateway
  http:
    - match:
        - uri:
            prefix: /outpost.goauthentik.io
      route:
        - destination:
            host: ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local
            port:
              number: 9000
