# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/namespace.json
---
apiVersion: v1
kind: Namespace
metadata:
  name: telepresence
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
    istio-injection: enabled
