# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.config.k8s.io/kustomization_v1beta1.json
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ./helmrelease.yaml
  - ./secret.sops.yaml
  - ./servicemonitor.yaml
  - ./virtualservice.yaml
  - ./destinationrule.yaml
  - ./pvc.yaml
  - ./service.yaml
  - ./service-external.yaml
  - ./configmap.yaml
  - ./networkpolicy.yaml
  - ./grafana-dashboard.yaml
  - ./telegraf-proxmox.yaml
