# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: influxdb-auth
    namespace: monitoring
type: Opaque
stringData:
    admin-password: ENC[AES256_GCM,data:XCdgX1+KVq1ygNMis1j6nA==,iv:LU6DlERP2vUlCc/w0g/IVUxt2a0SaUq4gesTCrmEWPU=,tag:dYAeUxd3Rja3f2wG3bEGRA==,type:str]
    admin-token: ENC[AES256_GCM,data:XszS/fYFUiuJB3sf4WWKUdxRiJRl4YY8uL2/WQ==,iv:p554QNrtFbvRt6IexDc7m1/Pfm1P+2UyC8pHp3G3Ay4=,tag:9gR3+bRxCUeXXnuVrWa/0g==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1cUNEU2lGc0k5NjhveFFD
            OGQvbGtXYlNGZ3V6aG9oQjYzR3ppY2ZObmhBCmtyYmZIU0tva25ORlpBTnZSQkdV
            T0RkVFFpZmwzaEZCQUdTMTZQVmNTYnMKLS0tIHQvaThSS1hHNVRzaEd5dnZnSGNu
            MkM1RVZyay8xc2RFMDg2Z29VOUVROTgKg7ujThdh8xrEswjhdDHwIqT+k6yRwXn4
            V2c5xbNOc0hE1OhNqDfOJd+qQ0PQnNfcSvjQxsPIkbzST7MumCmJSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-16T17:46:40Z"
    mac: ENC[AES256_GCM,data:GUZCUPaHPwgqy1iLEH3y87HACBy3VB68/FGHpNIpydv8hHcxJI9+3uJxAdle7JAPbuOYniRIaE9z4/B2n99LEP+l4j39aACjl9MNSQnzNu3l6NViWf2enWBgAMNHREhPc5V7ScjX5enztBnoFajI9FNmegwGjDwQWZcD2ZIaNjA=,iv:uF31EnPxC17W/OeUU0SQKOthkKLsY3ZpJ7mUoPgOgcw=,tag:nl0rUZFPcoeKfHliI5xhbg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
