---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: eck-operator
  namespace: elastic
spec:
  maxHistory: 2
  interval: 5m
  chart:
    spec:
      chart: eck-operator
      version: 3.3.0 # datasource=helm depName=eck-operator repository=https://helm.elastic.co
      sourceRef:
        kind: HelmRepository
        name: elastic
        namespace: flux-system
      interval: 5m
  uninstall:
    keepHistory: false
  values:
    image:
      repository: docker.elastic.co/eck/eck-operator
      # datasource=docker depName=docker.elastic.co/eck/eck-operator
      tag: 3.3.0
      pullPolicy: IfNotPresent
