---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  interval: 30m
  dependsOn:
    - name: istio-base
    - name: istio-cni
  chart:
    spec:
      chart: istiod
      version: 1.28.3 # datasource=helm depName=istiod repository=https://istio-release.storage.googleapis.com/charts
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    env:
      PILOT_ENABLE_AMBIENT: "true"
    meshConfig:
      accessLogFile: /dev/stdout
      accessLogEncoding: JSON
      enableTracing: true
      defaultConfig:
        holdApplicationUntilProxyStarts: true
        tracing:
          sampling: 10
      enablePrometheusMerge: true
      extensionProviders:
        - name: otel-tracing
          opentelemetry:
            port: 4317
            service: tempo.monitoring.svc.cluster.local
        - name: authentik
          envoyExtAuthzHttp:
            service: ak-outpost-istio-forward-auth.authentik.svc.cluster.local
            port: 9000
            pathPrefix: /outpost.goauthentik.io/auth/envoy
            failOpen: false
            includeRequestHeadersInCheck:
              - authorization
              - cookie
              - x-forwarded-for
              - x-forwarded-proto
              - x-forwarded-host
            headersToUpstreamOnAllow:
              - x-authentik-username
              - x-authentik-groups
              - x-authentik-email
              - x-authentik-name
              - x-authentik-uid
            headersToDownstreamOnDeny:
              - content-type
              - set-cookie
              - location
    global:
      logAsJson: true
      meshID: enchantednatures
      istioNamespace: istio-system
