---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app ztunnel
  namespace: flux-system
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/component: ztunnel
spec:
  targetNamespace: istio-system
  dependsOn:
    - name: istio-base
    - name: istio-cni
    - name: istiod
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
      app.kubernetes.io/component: ztunnel
  path: ./kubernetes/infra/istio-system/ztunnel/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: ztunnel
      namespace: istio-system
