---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.config.k8s.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster.yaml
  - databases.yaml
  - db-user.sops.yaml
  - hunter-user.sops.yaml
  - minio-serviceentry.yaml
  - object-store.yaml
  - scheduled-backup.yaml
  - secret.sops.yaml
  - service.yaml
  - superusersecret.sops.yaml
