# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: postgres-superuser
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:juVuI8UPmTadS+vumFTNbZfwGrF/jTBtvA==,iv:kIFORHlyUG62GGerAgNvyOxXWQh+/DKKoyQNcUKPMV8=,tag:jT3jeZvgML0zKBsXm9IAug==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0UGdpd0lBL0FMRWd5aSta
            eXR0QXpLRzcvRHBuSTBmR1RxUzBjOENxQkFnCllSVE9KWWxvSHQwT055b01xeGg0
            bm0wYzZOZXFRSitVamVQdHI2b0xaQWMKLS0tIHk2elFKcy9jM1Q5YTNhNFd4WVVF
            T0FyTU96SzNxOGZrQkFmTUE5eStBTkUK39ubBc1XqN2Z54FodGLAiWE5rwrh84Jq
            U7AbpPVyFOY2R44A4ND6zzyiYyGqfsq7kEs1c9l5N2gYsCsLHb7tiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:28:47Z"
    mac: ENC[AES256_GCM,data:S7eFvHtfjsHJp6vQZ0vjBLRBYW8RhQfqjYsaOMumxmOc6wk0E5+Lj9g9wdX2x3kFnTE63ffxWshNh2fT0qSxgb5VI+k1PRTh8HlA+spkRfyW+kpHvHn6B93YRmU0vEoqWbG8aqvDUyWkcJuGLUqL8D81iyL1WGDDr9+61UNFiFU=,iv:AZVZGJIXBPIH2hCTaZesU/sUyNijNlrRt9pjUz2Gbpw=,tag:4reLC0/rN05OpGwTTFFdxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
