# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: harbor-db
    namespace: harbor
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:Dg9Z1bt7,iv:TtRb1tv73rMz1X1O4g2WTNwBci+jNQVRafDdbDSMgpk=,tag:T6JFHd90p2a5chxED0jxNg==,type:str]
    password: ENC[AES256_GCM,data:isU8xPDWEbnUNmdwnQmT,iv:QRuYkDucWvwsHNVVkCi3Fk/aY9Pgj+moYHx3gQ2YhGA=,tag:Q7zwP7n0o6QQm23xasmhKQ==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZVpkYUFpK2ZoMmVKanVh
            MTEreSsvbnkydGg0dmlJWE1UMmgzamUvYldVClVhWHltcXc3a3UvcFpJSW5wZ2p6
            eWZ3SjVSOFNUY01NWHFRZ20xTDlSWUkKLS0tIFMxRStRZWhqUUc5MUhQeTRVY2tW
            SlozM3h4Q1lKbnMvZFpIaExRaFJOTlkKOmudcptRnUW25CgAiwkjN7xnYKS9tGQ3
            UDcJM3zprx6iqXXV2b7l8Jtxcn5S2SPrIXJor99+Gpu9Fi9J4T4ntg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-20T03:12:00Z"
    mac: ENC[AES256_GCM,data:hO4yjtO7syBdVQ+THzeY5eUKqhBCUABxLQ+UpXMkrVrj2H5oDrc/gCAH082c0b/gBxq4KurN6PwE01hLSyeH7Nbj8P3xP0vdcBSaERw7p30phSq9btMdAYFqYU5q+JLjQP34yf78PX/R0SvY1VgSuvL3sfLHYODkzyZ39eVoMQ0=,iv:VykcQWA+DBl/51KS2oBGIAqNQs6v9FqxSAEjR5WlEow=,tag:uEw0WamIVVpfutZ1ysodQA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
