# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.config.k8s.io/kustomization_v1beta1.json
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./config-map.yaml
  - ./dragonfly.yaml
  - ./harbor-postgres.sops.yaml
  - ./harbor-minio-credentials.sops.yaml
  - ./virtualservice.yaml
