---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/master-standalone-strict/_definitions.json
apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: barman-cloud-catalog
  namespace: cnpg-system
spec:
  images:
    - image: ghcr.io/cloudnative-pg/barman-cloud:0.5.0
      major: 16
