---
apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
metadata:
  name: cdi
  namespace: cdi
spec:
  config:
    scratchSpaceStorageClass: openebs-hostpath
    featureGates:
      - HonorWaitForFirstConsumer
  imagePullPolicy: IfNotPresent
