# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:AINafoLV7q9rNbWz,iv:HQrq7u4+9IXRq6HbEhPBZA3xJ8LQ0yV630SKi/n7rEg=,tag:cWgCPM3/+NKnPNDgmK/DEg==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXMHJ4eStJMUlQSjJOTEtR
            OUNLdzllMmtXME5XWjJkSVB0cXM0VzJ2RlNBCktyeWhWNk1PMXZYUHkwMTZiRkpO
            aVpLaFgvdlBlNmZVTGxCdlJLNm4wM2MKLS0tIGZ1b1NkMnFSNnExUDJ5SzhlVGpQ
            T25LV0dwamcvM2lWZ0RLWEFwc0NSbXMK79EWHJdU5XFjuizYHSqVZ5z2CTsXlad7
            HoClLr+RRai+p+ijw+G6iRCQtFlmzplOwclTo/wLkglvbG7tJ6MWow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:28:47Z"
    mac: ENC[AES256_GCM,data:TBrSgzV2kwDyRj3pYvuSYlsZlE5Ue9NEyg6zfT7TqkwKP5DIuEnNpG1qy+NT97aGjol3fAVnJpAi+l31qDA4uv/nUWabrkEIyBzGl1apyr+B1J6opz0K9cqSSdVTzTwQRVAeqRA5txPxpr8IB2smG7c5A9GssHnkitowAZUFH88=,iv:AcK2/z8aBgTbOpS0oA6vDg+BM4t1i9vSIYSgTclRe2c=,tag:J8N7LvRZZorjfrAD3Bp6sA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
