# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:wK+IvyjHHT/HzHMP,iv:VDpYXLcv/FuD/uvtpAm79UgfiWqQ2rLPEcvJDuHKguo=,tag:EwuWhLwhMM0SDiSUXYxG6Q==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQkdYSlRxdlNBcER4NTRo
            Y1g3Z1YybmxOZFFkdnFOblB3RFdaWE5qeWhFCm53VTBPU0RnWUN5T0RwUWNBT3dS
            WGh6ejZiZUV5WEo5NUlyOW9qVlV1MkUKLS0tIEdOdTkrSmxzdDA4R1FYUmFFRm9V
            SFpERGk1TkliUGlPelZxbEI5dW9zcUUKULY1VmZH3glKTBVffr+QpRLoMR4UXpJk
            BPcCXkWfvduS5D6qFpmURY+zaROdJ8ZFFkyexxe+I5epNVvolJhEYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T01:49:11Z"
    mac: ENC[AES256_GCM,data:wTkwI5vOtT36CpI5OjHiye8niayDJEPqBgmKkft7plrMCfIPKKWPAfOdqBC5d33hc0mMWk0RKYkAxB4Jb3/mOKddG6INdIZKQUBT/dt2qXc3H3QM3u0UEhPlKpkFS+UBFKmYp1gyLCBvn18nX6bSXaDVwnMYnnLNk0Qt2q3kqE4=,iv:9+ai8S1gsvtyxm29bLQH917Gb2kzkRN16laIdZRFR1E=,tag:67+S7LZIj6u60kwZA/9c+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
