# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:0PPZoH4dXcoZ1aI4hPjuH1NyPA==,iv:Og+Dg1XDOZErjYzmd5+PkwXNrg19E9JEurTuoHypWBo=,tag:bu6B7yxwu+hnas1C0aXV8Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:2GDjbcnrEVIcykAyGncA/56QTKAuAA+9yyM1KHPn3wfQFGO5,iv:RSmHJUCFLbx0SFPD41tlMah1vTtBAesKo3AVFdwwSgQ=,tag:0egdvIasDIKKtILAfN9tfQ==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:OZ6pko5b+JaIhAxwgEb5pWw++s8=,iv:ZfPQysFWh6EHCJNY/9sRa3p8VwBGDyufK4PaAuAIyZY=,tag:dRlgr9OT0ltwthStr3beHw==,type:str]
    PRIVATE_DOMAIN: ENC[AES256_GCM,data:Jhe0E+uiaAawTRCPCA==,iv:+wDXbekKiVTjc6WExFQ73Uosd2fMqn6X/tD+un5nNZ4=,tag:lH+In8lGP8TQhhJwcU/mWg==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxVFUrUzk3V3VNTURpM01B
            UEZXbTY0N21USnBNVG5IN2FQaGJDY0FXK1djCmRYSDRGN2ZtU0xkM2VrdzNxa29P
            SjBzM1VZVFE0ZzZGUWVDZkptTnB0S3cKLS0tIGQ3MXBvU1gvMjZrZk0zNDBXcjJF
            WDJWVXdzQ0d6Qjh6c0Z4bWw2KzlYVEkKJS5XZMCVmUCHm4/Y2pGI3JOxshMNQMuv
            0aQF0DPKktqyOzW0W1QcXEb/EmlRzPcHdaU0YHGd0YXCm5YtU+8YkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:28:47Z"
    mac: ENC[AES256_GCM,data:hQvc5b3B2xC5BpU2OTr6ubKvELzoUsk7ze6I9bEF64SNim1hlRrquDyZud0lId+YX0tSQYhe/TRjFMtMBhgXppEVp2bnGpoc2MIyxL/FAWxMQpSSCPwqPjKd7jkMH09ko5Y+61qugd8RTqN1ZkegljrWlBrqvswwx0IAIu5i46w=,iv:/cwRrs+U6yzrIqEok5ROdG+Jbqqqa+UR5UvgxsRq/BU=,tag:h/iQp5Dl1kq9Wmp5Dzqchg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
