# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:AfChw4lqxG8VxSFbVJgXqDOWfw==,iv:AgtgHZ/+JuMf2jI9XrW+JPK4uddZQH5d0gveMzzBCPs=,tag:3UZNGZ3qmwfK7M9LJ9z83g==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:VIq4ACWuVu2B2fCRb7S0xRCPOJMX4vNJVyJh4KWCbWb5OdLW,iv:1hgG6GHZwSBYnDyiLwwbpxkmQG5O/yBFQ0xNVPpJv74=,tag:d2URtWtoWAxJ0bztMeSQpg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:mmGpuGjahaZKm42bI52yxN/3dm0=,iv:fqNxKBnvVGOOiK/iDqQoR4gBkqKtJHBXtrkSM6VgS88=,tag:QmhphGzurM2pBwCMNgbYCw==,type:str]
    PRIVATE_DOMAIN: ENC[AES256_GCM,data:dCw4xM6X5ID13aurdA==,iv:fu4LMWHB1rHKrCU/5VpG+htjJYcPEHpQXpVDRH0OkYg=,tag:+48eMUOHs2U3NmPje2wrHg==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKanFyRUJ4b2oxQ1hkRTRZ
            Zjg1NXI2Y2t1MUI2WG5qMlNBYzM1ZkF4RzJJCkREOXJEOWptZCtRUk1veDM2YlZO
            TXd0N1ZlTERYVkpBR2VIT0RXYVdiTmMKLS0tIEZsaG42TC9RUnVjUjAzVHhpMkxv
            Z0hLTDJoMHZVMjhjQUZ4dHRicXB5ZkkKUcehKycRvAzbnv1ULLIfiASyir3A3MTX
            k9R40S3BDDnt5eCvcRzrb9IDQqJ2LKM8MeZi+GtYMtfIbpgxb3VTmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T01:49:10Z"
    mac: ENC[AES256_GCM,data:TnXriZj48lNebvz372dLeTOBow8ld4iWy5W5fd11S9tAJSLfWVLMlfvMKgSRTKNo2tyh1DPr7m+eEXPFC/k5x21wsAsgDHGmyhoTi1EjQd9gYCmL49Q1388N4egqIAx/hGdShdTUpqePhXDkCXkafccrmBRNFKTfo502kkx1HKE=,iv:W2k8ZblJ6memVVKHQzzxQURp+A2KKmWkySOX2aMF3M4=,tag:Z6wLReQ78Gz9EVg0k+MjcA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
