# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/configmap.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings-user
  namespace: flux-system
data:
  SETTINGS_PLACEHOLDER: settings-value
