# yaml-language-server: $schema=https://kubernetesjsonschema.dev/master-standalone-strict/_definitions.json
---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic
spec:
  version: 9.0.3
  volumeClaimDeletePolicy: DeleteOnScaledownOnly
  http:
    tls:
      selfSignedCertificate:
        disabled: false
  secureSettings:
    - secretName: elastic-authentik-oidc-secret
      entries:
        - key: client_secret
          path: xpack.security.authc.realms.oidc.authentik.rp.client_secret
  nodeSets:
    - name: default
      count: 3
      config:
        node.store.allow_mmap: false
        xpack.security.authc:
          anonymous:
            username: chastened
            roles: superuser
            authz_exception: false
          token:
            enabled: true # Enable token service
          realms:
            oidc:
              authentik:
                order: 0
                rp.client_id: "elasticsearch-kibana"
                rp.response_type: code
                rp.redirect_uri: "https://kibana.${SECRET_DOMAIN}/api/security/oidc/callback"
                op.issuer: "https://auth.${SECRET_DOMAIN}/application/o/elasticsearch-kibana/"
                op.authorization_endpoint: "https://auth.${SECRET_DOMAIN}/application/o/elasticsearch-kibana/authorize/"
                op.token_endpoint: "https://auth.${SECRET_DOMAIN}/application/o/elasticsearch-kibana/token/"
                op.userinfo_endpoint: "https://auth.${SECRET_DOMAIN}/application/o/elasticsearch-kibana/userinfo/"
                op.endsession_endpoint: "https://auth.${SECRET_DOMAIN}/application/o/elasticsearch-kibana/end-session/"
                op.jwkset_path: "https://auth.${SECRET_DOMAIN}/application/o/elasticsearch-kibana/.well-known/jwks.json"
                claims.principal: email
                claims.groups: groups
                claims.name: name
                claims.mail: email
      podTemplate:
        spec:
          nodeSelector:
            kubernetes.io/arch: amd64
          containers:
            - name: elasticsearch
              resources:
                requests:
                  memory: 4505M
                limits:
                  memory: 5446M
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            storageClassName: openebs-hostpath