# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: elastic-authentik-oidc-secret
    namespace: elastic
type: Opaque
data:
    client_secret: ENC[AES256_GCM,data:/9DIdM0P5aUdVLp99JapeGkTRMt3t8e6t/EFKJlZUEEqi2Ia5XE10GZqgVejNVWmMQtl/RlHVEIuBLZcfM1tKyE9QSKr7C+0G22zGXu7zeutAHY3PAdgT8nIut9JtwXYaeQewvUwHBZDCBGVnDEPPQYbHkglCOk7nNiRa8z3vZ8=,iv:f+jbvdZbPV0qoAippGyPj4ce3o2dZG6G7aXOajbxCpk=,tag:QPXghkutd1fxhj0ruf3z3g==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVR2VVcDZGcEZxUmVFb1F2
            OUxpRHExekpwQVdtbWpsbHNJK21GVVRMNkJVClVBTHNhNkFUUDVCR1hMSU5yVzhU
            RituMzFCOERtc3JVVWdUbTd2SWJ0V0kKLS0tIHdBcFJ0QndOZW94TXJscEFQU0xL
            MjF1Z0d6QVZJbEc5TkIxTHlDOVV2WjgKbipdRhsWHjpKeMjTUZLGiNP3wC3V0Cha
            3GJ9X69wGV9eeVR3PEMTk+VeAbOAgiOP7uUvv+GNWl6DTNoQYieLsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:28:47Z"
    mac: ENC[AES256_GCM,data:EqfuQjeu4Z7rfV9y18dYAvN58gTJLNzRI2rKULq+j+ZcOFbDc7CEAGG07NZsRPD4A5CcG6EQ+TNlhJnt4KknJF4qMAbcu4jeC/6G9xhjtTBC6L4lOyJ59EaXy6Tx+ocrSgLKMzJQ4wD1dpiz11mlC9DjOvcCY+3VfiyhNa5gRFI=,iv:EYpFsWQQNWNQgsw0vb3N6+me9bg5bljJpUYfps28UV0=,tag:DAdI10A+ndqKgXf2P1lvBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
