# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cilium.io/ciliumnetworkpolicy_v2.json
---
# CiliumNetworkPolicy to allow cloudflared to reach istio-ingressgateway
# Required when running Istio ambient mode with Cilium CNI
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-cloudflared-to-ingress
  namespace: istio-ingress
spec:
  endpointSelector:
    matchLabels:
      app: istio-ingressgateway
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: cloudflared
            k8s:io.kubernetes.pod.namespace: networking
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
          rules:
            http:
              - method: GET
                path: "/"
              - method: POST
                path: "/"
---
# Allow cloudflared to make outbound connections
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-cloudflared-egress
  namespace: networking
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: cloudflared
  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: istio-ingress
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
    # Allow DNS resolution
    - toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
    # Allow egress to Cloudflare edge servers
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
            - port: "80"
              protocol: TCP
            - port: "7844"
              protocol: TCP
            - port: "8844"
              protocol: TCP
