# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-tunnel-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:sy1bItwPY7j1WsZFVRPPR3uMGFlLiumQOrt6rYJwzL9INypy,iv:YpIkcDrATRLSt5spEQ0MV76IRW4EemrY+hRrl6vSYio=,tag:cyK8umAKC81JLRITi51s2Q==,type:str]
    credentials.json: ENC[AES256_GCM,data:oHV7Pm37M3I+2L85gvB3VlbIPYSpiyV+YXOsiLAX0TwSO0yV6Tr07WbQ+wnPa7KOdxwJiINCy5ZRNFfFdTf+/XmPCBM/p/q7y+WOamGFMwprKmXz0WUor+T748nNJP8x/kzFz22Nbn3F+0s0gONn55ruS+e99TGD1jTQJw/8t7VAgiyxmg8PgfMuZdvOUeW4WsKf7L5omB11yWuZ9KGjPK5utBvRx8Pe8XO+qYz+fQ==,iv:R9Ldw8GBXXs6pDWfYVf8/F/bafSzvL2iK7G0tEIZavs=,tag:TqvtMy7MPIcHDSy3ydhA8w==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmR0t4L0lrU1c3RXlPK1dJ
            UmxoclJjaFlncGZqRjJRQm83T0t1NGc0b21ZCjNpRHA1bnIrOXRyNzduZ0x5SmJP
            Uko1bSs1V1kvYTZ2YjVqclQzVXVUVGsKLS0tIDV4SWN5RmhBVmhZdGhCQlEydkhI
            dGhuUnh0QnhqTFZ5dG9wcFZKaHlRM2cKx6rI5a+NFNvufMm5NXrbLV7//4dkOL7S
            DxWTWiM/uRnSyZMFmD11MhKFBKXT6ndS0k5YM73dEEV599rE1J1HkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:28:46Z"
    mac: ENC[AES256_GCM,data:tI3uIsNoSwkt5rwbNEs2o4uebC6hx8Ycj6LQxigqaDqEIY5uo3AroTwRzuBv/1L9NGrvAgKbThvN7K9S6INtIUqEjxRI2PxAQCSgNMYZLjovDIBPhkCrHqnBaXBTTcFwE5YUYTGxYxa8j8tHptOayJ7CEcrcqOzlNVfRRIb+Sas=,iv:7zH/mXuTU2PSbYqWHwr6tvmYtS/QW+HZkSBFXbbvL38=,tag:WTMyf5ToGHHtYWWi6C6TAA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
