# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:ROcrwZzE03Ihboi9tsEC2mV2Bm/JIgpc,iv:ULJ2pSknxh7p6FRtt5MY91OucBhMfYGqWpGXWX/ktR8=,tag:S92AyOKk0mfIq9IayYiqZA==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEWUxuNXRJMEV5Z2lFNUY3
            S2F6Uk9ySXppMWFrV2N6MmtQVFRhaEIwQ2c4CmhUTWFJUVJCV28ra01EdUtIUzVl
            SVMzKzd6emR4dGliY1BGYU9GUFZiMGsKLS0tIGlPU0szaE50eUIzVmNXT3NqWkY1
            UzhueGcrSVdDRWQ4NjBXWm1pempTVzQKcxOV4lNs2OXLoQ8vZzCE6ZPw+hFqxi3I
            Uyygwj6/zntYNw+b74UKpjFUlNBASaomw/2CRwklu7g0czM1aHVteQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:28:46Z"
    mac: ENC[AES256_GCM,data:JlzX9zlOCM4+OWa0MOqT/LzeMxQdqJvjSNkIKzdzCxWAqlMjKvL5vrC2VaOg2YQT05PsnaKxm4t5Kz3bteJlFyz2MlqQiJcP4GClp9axU4ppZ7iJzMuRLAAQKWNcax+1ONPPbIdS0ZFb40nMvRt8SLFG76O7/ZJsw+x4+UQwiYM=,iv:nVPjGvoyJ+pvtWR1F61HPXKsSKu7XVQsEoRSUXUqe74=,tag:fSbsVCK0Uy31nqyUmqTH6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
