# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/configmap.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: open-webui-config
  namespace: default
data:
  ENABLE_WEBSOCKET_SUPPORT: "true"
  WEBSOCKET_MANAGER: redis
  WEBSOCKET_REDIS_URL: redis://open-webui-dragonfly:6379/1
  ENABLE_OAUTH_SIGNUP: "true"
