# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: openwebui-pg-secret
type: Opaque
stringData:
    aws-access-key-id: ENC[AES256_GCM,data:45qzGtvoY5ATst9Z7bbzUYv0ytM=,iv:ZHX0xOIQazRtBzC2ihH+hCRbq/Xot71gvfXo1NAnlEI=,tag:DjtHrSH11bcHJZvUFQKsKg==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:UGUw2Cum9SvOvlOduO8WDXmsbemdRxyycQp6yKATdw8pT+mmHda94Q==,iv:UyxZqCrRRNLAQFTYdIE1Db7XJIeRXRWo9j9eK8OZBzI=,tag:BGeTjbde1AMI8thEwtPrNw==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGaUJQQUkzSkNTVlQ5VExB
            YUdMTThDNnNmYmZQYTlqM1lRSVBEYXV6TFhjCnIwdnNxVm5NaGhZOTlhQm9BNUow
            N2ZhQ01oWmNlakREMzBGcm4yZm04ZlUKLS0tIHZ1RnRFSUxwMVpjeVR6MFVMUkZ5
            Zy9uNEdSem5MZnU2dnd5NFd5b3JtOWMKfAc52gT4k8qpgk7lLh3seNCN/npnblAO
            RSSkb55VE50JS0RN08Lr4Tjp+mUZaB0rKbq25jIg7YMdOyKnR9uWXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:28:47Z"
    mac: ENC[AES256_GCM,data:I8sZbjcfkkpQEEQ4WHlm02e6P+pf7mpiWh+yxUgvX2/1AbPN/nTJHGOCeytHO9r3FeCE+qjne9jP/mmnReXUFdqFw9iBuBDaZcTgPhh4aQtfmgC/ciCd9hYfFb0h2p6cCUP94XYRSNGnzMWV/9X55/spExZ1VWvTnONVsYH1ERU=,iv:e7ZX96rQx1kDi2T6toL107HdQixMy/WMs70baiZNtPE=,tag:heIT40XKPJXdozcRATsyqQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
