# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/dragonflydb.io/dragonfly_v1alpha1.json
---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app.kubernetes.io/name: open-webui-dragonfly
    # app.kubernetes.io/instance: dragonfly-sample
    # app.kubernetes.io/part-of: dragonfly-operator
    # app.kubernetes.io/managed-by: kustomize
    # app.kubernetes.io/created-by: dragonfly-operator
  name: open-webui-dragonfly
spec:
  replicas: 3
  annotations:
    sidecar.istio.io/inject: "false"
  resources:
    requests:
      cpu: 256m
      memory: 256Mi
    limits:
      cpu: 600m
      memory: 750Mi
