# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: open-webui-secret
    namespace: default
stringData:
    OLLAMA_BASE_URL: http://192.168.1.77:11434
    OAUTH_CLIENT_ID: hw0H1Yr1ktJbzwsdJSd3kYExOqFSjkhm7QhsFQmz
    OAUTH_CLIENT_SECRET: ejCYW0LrtIwWlZXmrQ6WMfXW9I3ERtUt9jQaqGAFPVptu8mtnrMOFnwva2VfdCmeMJs6jv1Tz1RnBhm3ZnJfskpBWunESHiZwsMw0oKAq2yq82MPE6wBqrzUv2pilaLT
    OPENID_PROVIDER_URL: https://auth.enchantednatures.com/application/o/open-web-ui/.well-known/openid-configuration
    OAUTH_PROVIDER_NAME: Authentik
    OAUTH_SCOPES: openid email profile
    # ENC[AES256_GCM,data:AIn1xELlC/+JkGdSMsKJ3x7y2j4XNHcrRQ==,iv:rVhRBfdukJlxcRhd16kG6VHojLdCmGnC6jO7XM8+Iiw=,tag:s4vcB9RMOL33DMW+co0wtQ==,type:comment]
    OAUTH_MERGE_ACCOUNTS_BY_EMAIL: "true"
    OAUTH_ALLOWED_ROLES: open_webui_users
    OAUTH_ADMIN_ROLES: authentik_admins
    DATABASE_URL: postgresql://app:HannahH0ney!@openwebui-postgres.default.svc.cluster.local:5432/app
