# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: postgres-superuser
    namespace: postgres
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:qpjQ1ilW+G6Fh1+ILvzj6yXheKzpsvGmhA==,iv:2inzVUswVoVZn2XhLk0NVAUMQT++Zk4QcM8dzoZmpkQ=,tag:GzBAnI94M/EOPIEoTZV7bQ==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzQmRMWEhuSk5pc2MxWjlV
            Tm5qa3ZkdUdSeCtPWlRJNWNuWC9PdFQwRUc4Cmg3YXlUazl1b3FsbjltYjBDKzVz
            YUVSc0FOakJiMnJ5d0R3ajhFZWYrUWMKLS0tIGhBcWdIQTArRVgzM21VaFEzekpi
            b3ExbzB1dmFROGhUeFdKM3BVdmt6TjQKhzs9k2/AM2ainYBEmqpAnNeAxmwb2iD6
            V8VPQpM/9b7s8yCnzxRhhITLyqmUmIhbK4CrfhUEORjeOM7W6mtqoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:28:47Z"
    mac: ENC[AES256_GCM,data:HR6E2xBXvZA1qmLZm0Aw6J5f7aUkEMFMPNYoUSX9V6L1vP1RpmKRRtReoVMPH9lT3LDDvV8hRKSXvwAv3U+kblAMu+XysyP6Tps5ijBYa2INSVnXho1kycyvXfyXT10PrHp9NUUxNnXuROna8CyqUl1uVBWGvAHrU0RnUAfbqcc=,iv:ncXdxKkIN+/2HggAkPSxM1EiHVmQ5eJJZSOpGXgCkOo=,tag:WS7EoB/mQ5PD1X5fyQU8Zw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
