# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/configmap.json
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-bucket
  namespace: monitoring
data:
  chunks_bucket_name: loki-chunks
  BUCKET_ENDPOINT: s3://loki
  BUCKET_HOST: s3.${SECRET_DOMAIN}
  REGION: us-east-1
