# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: loki-bucket
    namespace: monitoring
stringData:
    ACCESS_KEY: ENC[AES256_GCM,data:GW1pIwDAR6gjiDvYh/EowcK4Jvg=,iv:mGR2LE4aed9DoNkMelmMI9aBCPGyf8YiH/QwsJe0VEQ=,tag:AralUfhlO9xjuhEKfM1WYg==,type:str]
    ACCESS_SECRET: ENC[AES256_GCM,data:ugk6xDGHMnK4aAzLvwHh6tF4yQB2mG7/SNVY3ISpxXl8fgkfZeSgaA==,iv:dOjSgZgF2O3ljRTohCz5wexvZJuvbGxOot2sM9FgOQ4=,tag:Wo/Vys3c/xyUPGU0HqTEeQ==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENzg0ODBaMk0xWG43bzI0
            ZVV2QjZlQUtRWmFUK2VZWmdwZzF2cElyZVFvCkNRaEdiSHl1NFlQSWM4Y29haTg0
            ZVVldjFVRXRzM0p3QmNsN0JoeExsZk0KLS0tIG5UT3dpWG5YbXJtN1pSOHlNRVhn
            T3V4MUxCeDBoSSsrbkQwK2JjU0wyNzQKL5nHP99aUsijJsy1vF/y2mh5EpjF4Iom
            bT4MSbrANLna5Rh7Gd9S78E+RbdwXVFUaqyaj2l1FDUifKXZZN6GeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:28:46Z"
    mac: ENC[AES256_GCM,data:seUis02URRERowxdGSyx9hYIp+eM/rIu3P7FEttnzLdhQTruoI0kjKDdxb0yImvcPqGJ6il77dtDD9k6LOtA4KKWnrYYeLQaTWyDHp9d9hua82RoyoH74zU2zyeWaH+7E3GcQKTjB5hzWtSddwfHp5e+FW0yZOuJQq491O3qt14=,iv:fioKYLSox7GmkXuMOL6OtNXoviLYfXU2P8OMcu0IGq0=,tag:pNGvM+quehW6MWzNFjotow==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
