# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/networking.istio.io/sidecar_v1.json
---
# Sidecar configuration to exclude admission webhook jobs from Istio injection
apiVersion: networking.istio.io/v1beta1
kind: Sidecar
metadata:
  name: exclude-admission-webhooks
  namespace: monitoring
spec:
  workloadSelector:
    labels:
      app.kubernetes.io/name: kube-prometheus-stack-admission
  egress: []
