# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.config.k8s.io/kustomization_v1beta1.json
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./scrape-config.yaml
  - ./rules.yaml
  - ./virtualservice.yaml
  - ./alertmanager-config.sops.yaml
  - ./discord-webhook.sops.yaml
  # - ./istio-config.yaml  # Disabled due to IstioOperator CRD issue
