# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-postgis-secret
    namespace: postgres
type: Opaque
stringData:
    aws-access-key-id: ENC[AES256_GCM,data:W5aBILQzqyAXphHbmdB76RrjzRU=,iv:2nFb4PaSYvxwzqO1eeSgjnkk6hEOS1NjYsTneNQvRc8=,tag:dYI4vR8O1MNqRRuOOFj/uA==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:6vFLsPg7M4jMsy+DYbvCk9SFnJaolk1oJ5Oqq9JKnOy/1z8yFpaZpA==,iv:p7OMsiF/xyweB2LsQ3G0E+Qjov7S+NkFFp2op3Mfg/Y=,tag:Gs76tD7GYq6tZ7X61A0FwQ==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUYUkzYThnQ09MV2tZV1g1
            QkZRYVV0ay9HZXFqUWJDdnpCSDJ4LzRwZmhZClAybXpxVnFSTkNUOU03OHA1S2dL
            Ry9ibVM5WXArOGN5OTFCeVBSVnlyMHcKLS0tIGhVazdBOGJMSFNEY1Z5SUhIenU1
            TE13TmpiZzhDK1JxaWtCNnR1WTFNVHMK/M9gURjoowzuOEbFkbK9K90sb/TjDCp1
            Gp7KyQ18xfKaA0oqRex/+dwWYsKsdAp5AavB2oLhemntMirhnbOJGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:28:47Z"
    mac: ENC[AES256_GCM,data:T9ywXLvxDZLHWvHi+pyhewYpQ/W3ZO3Fme6i80Mz6j6efg5RcURR8KcOhTfLQs/qemzz8Rh0L3VF+r1rhY9lsI1tiUris9u2YawJbkcorMnx5GXGCtHc/eAgZvpF5qZa6k9WVX4ohRJiQ3ny0mG8msHAvzuQwrRwyulJGozIeGc=,iv:Elzc58Cx/kXo50Y1B5cq8yLBGD8ohCYHwuB+idbzKvw=,tag:6g1O0xFyIrM9lHZt1J1jKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
