---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/master-standalone-strict/_definitions.json
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: arch-linux-root
  namespace: vms
spec:
  source:
    http:
      url: "https://geo.mirror.pkgbuild.com/images/latest/Arch-Linux-x86_64-cloudimg.qcow2"
  storage:
    accessModes:
      - ReadWriteOnce
    volumeMode: Filesystem
    resources:
      requests:
        storage: 40Gi
    storageClassName: openebs-hostpath


