---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/master-standalone-strict/_definitions.json
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: arch-linux-root
  namespace: vms
spec:
  source:
    registry:
      url: "docker://containercraft/archlinux:latest"
  storage:
    accessModes:
      - ReadWriteOnce
    volumeMode: Filesystem
    resources:
      requests:
        storage: 20Gi
    storageClassName: openebs-hostpath


