---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cloud-init-secret.yaml
  - ./datavolume.yaml
  - ./virtualmachine.yaml
  - ./service.yaml
  - ./virtualservice.yaml