---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/networking.istio.io/virtualservice_v1.json
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: arch-linux-vnc
  namespace: vms
spec:
  hosts:
    - arch-linux-vnc.${SECRET_DOMAIN}
  gateways:
    - istio-ingress/gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: arch-linux-vnc.vms.svc.cluster.local
            port:
              number: 5900