# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: arch-linux-backup-secret
    namespace: vms
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:AGwhr+tYnLemeq5uXEscoJfPi00=,iv:nWSNpOjng0bnLmIbyzUR/EQSPWZTfcJkR/y3N/ebDgo=,tag:X8hKa37LMTuV+swrtQ3DlQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:swhsz1dRlKSwR+qzvVn3Hk4qBThtTm7lWRi3CFUpDwL3UBMdEutWaw==,iv:W0VUzF47WMg9vkTBMXw+ONvdf1yspb2z7bP13BciS64=,tag:C6AUL510XIT491FxqCrIqg==,type:str]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:+cipivdTOvyzm0Y4fBfJT2sdIBxNvXmrhDA/uIejVczcytxdBAWEcvl/b1PCwaJ1xSPLb+TlIKKFzFd5+U4uAzs2Z79joMoyPTfxdJ4PvQNUQT3R,iv:mTqQgtvqOuOnoTQHseMbzqfHx6Kc86D04AtOnCMElCI=,tag:oB0QRmpNF/Gz8lCIqQv/sQ==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbW1ydjBIdE4ycGlETk1x
            eTdpd1FzbzE5VlgzYW9JTEZSUjhPSU1xYTFRCjhEbUpyZk9vNHVtU01YbzZNbjI5
            UE9vakZXT28wR1FtakFYbmNhSUJ4T2sKLS0tIDFRSy9LSVpNK2w4QmZ3Z0pWbGdo
            RFJjME5BYU9FWXNBeXVCbTU2SHJNVkEKAI/6wW/kmwyJOZpZAoIk7gbLHMB2Zr3T
            N+C76/JrlNGANjwEv1XJf4s0cuGqROMhggVT4OK+PkYiENQvo1gngA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-16T15:10:44Z"
    mac: ENC[AES256_GCM,data:9+Ui01kJSVoP7DsNsDz3kcYW0zSkm8uIEegU9EHL0lGFWv4V6335pUCbgEfkvKonoQ3xoTAAhiuZCwbzWUpJjQ7Peawt39+Fzs+AYVkZnVXoX0e0uS3DuUel+22vI5zxjKul2pk3C5MLYk7AQUt7h93CNQhtcmelQ0W6Szg3mlc=,iv:FEHyaTixCLYDArRGBm9/vxZv7kSND9GK0V+CekEXO4o=,tag:2ymaGpLDPMpmvuykFGSeuw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
