# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
kind: Secret
metadata:
    name: node-watchdog-ipmi
    namespace: kube-system
type: Opaque
stringData:
    host: ENC[AES256_GCM,data:DSZJ3raALn9qNBCS8A==,iv:axpJIVv0/sHImPsLVEzAQYYOtmF+++0kHIwCJRev8Qs=,tag:7t8D4udUGhSyXenzSentUw==,type:str]
    username: ENC[AES256_GCM,data:kniYVhg=,iv:snMluj0m/8J42UvtxY6O6+VuSLzv6EBjfbis3je1jaU=,tag:C4uGA8RxRW7E9MZadYwPhw==,type:str]
    password: ENC[AES256_GCM,data:/OKs7M8=,iv:RAqFzw4e/kFFRKQVGq5iGJB4i9LuEUsZ7r9xhP4v8kQ=,tag:WD1IfeQ5gwTX5svzXT61IA==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3b2VqZW5xY2hodE5ZQ3Mv
            UlE1MCswUjFoOFdCV3ZYN1JJU1VoN2NuN0IwCldQZEtoWTg2dHJJYkpidWQ3NHFZ
            NmRqTFBhR0FjeWxmS0Q5bTZFaGYzeEkKLS0tIGUzR2lmUUpJSDhKVi9WZ1lJeUZJ
            U1V0UWpCellUMnJCNmNlREt3TGsvMU0Kok27PiW6Fe6aw9KoKzj/ET5qbuNIlGq3
            kuNWZ69cLBgB2adcyv2s1ULcRyHdVI8GqxSPIDyEZZ9jJevpiIryFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-17T05:31:57Z"
    mac: ENC[AES256_GCM,data:wx2IlW205ZFXkc9n1tnSdcPnkAsgwUdbPCwDHSoL64/DK/aDiR+mkN0MR40JwtbSAFEhy5wrTpuScS4Bw4aXKGWwKPSEhUBu1qiHabI667siQnyZQoXBXTfuBA0xihCHtKivudHrRZZUKrkuD4xRzFELNejCITkl8/hQNnQtXV8=,iv:TKBLikfBEchjBgFhm0FCgV93Ep2fRDRgWKF8pNxKhGw=,tag:iOz7xRYt1tIZ5/r0Ro0/IA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
