# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:iuHJCmT9P+nxD12i,iv:K3dxPlrySxBhPWCBc921h4MxgtXmgOvZe0mJqbYCdA0=,tag:hegy1CliRF8m6dFtQb7M+g==,type:str]
    username: ENC[AES256_GCM,data:zmkGShFB,iv:DwbF1MNpZM/JabmIu/LVxcPld4PtIlPr6uVllQOug+E=,tag:dQNoo0/Xn+w/dZ4vCQeWSw==,type:str]
kind: Secret
metadata:
    name: db-hunter
    namespace: postgres
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITE5IV0MwYkFGa1hHbVps
            aDkyazRObXFlc3duS1Y4SjVSYkZSbTByVzBNCjh4S2h0d3N1NGFrNGVEeDdibFBv
            VjlrNzlmQWorK2pLTGRIVEU2SFJQNDgKLS0tIG41R0VHR01yOWkzUitCWGxOYkgv
            OWpNc28wQmszSTJFSmY1QTh3eTdXV2sK2tJLAfKyOEfPTpzssjvKld/prvZw6taz
            mtx1tHGEFGqcnVfgGyNjtgjg1rIpU3UgMM4u16NtHtqGNhWE6uZtSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:28:47Z"
    mac: ENC[AES256_GCM,data:q9m+cCIJ0dFTQbc8GC7mEejz6+LjZryM912vxB5L1xb9OH91MRivROpbIwCXRwnHS5YwadEQGaDxtDp+k+tFiifehsG2KUS4GGoA5Qk+kGjO0vb8jqxQONlHdurQM5QP0kwyoCbpJPXE6ZEpSqCDdwhftJcwBDFKaGNAQSGI7Dk=,iv:Wd2v+HGNbdu+tHtAbq0LAb9efrvzO0Lvk2DTeynIB/4=,tag:ZMZ1rgx36NCAxH9T/Dl3KQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
