# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:rVy+P8WokdqET5Da,iv:/zHoPmCTQerP0n5+ZlzeLY7yx6/uhTa7k6oRg3TFUbo=,tag:JLA2o67FBpIprWOslPQ0QA==,type:str]
    username: ENC[AES256_GCM,data:Mlul,iv:0cbYZ9XAF7NrOOCTTKKFk4/CYCu6usH1mnadw8mbdG0=,tag:65u5BF/22AWfI5yV8xJP1A==,type:str]
kind: Secret
metadata:
    name: postgres-app-user
    namespace: postgres
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWVowNkxCYnBMUnpKSzcr
            bFppTCszNUtYaUVLZmkrVEFYWHNlT25VZW5NCkMyNk9YQ3dKTlFPd2Rva05wRVJx
            MFphdzhSakM4MWp2WFFVVTRhN3VMSncKLS0tIDNXYkh2aEtSN1pMczcvaUhQVHhj
            QlJRVVUvV1FXRGNrdkRvUEpneW9oN28KnIgjLSqJmAX5W13jMda8W6DWs4gKWYRz
            5yU8zNR4TcvvA9eZCQTRNZ51zV+UlPkA4hnMeSM569ObLwLZihED8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:28:47Z"
    mac: ENC[AES256_GCM,data:bLxeWOaCcmWln5BAzPAZIL8oZ8Pp6CWs/05k+pobW4FMMa+A6R58GHoAC2rWweA98/kZDW4+paCcWcqP3cGervd6IHY+w2BcYhzW5y9zGAlIP4G2ehCE7TnK9/QcmfST/khA4x4vOVdNZSSLqvFM9evz8QZ47DIahR+rDknqx3U=,iv:Tdzx0la6Xpafmis+dRv1LOUpQc+2s7yeZLPgXTKe/Bw=,tag:kq7Vz7xPggFO4sOppcktqQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
