# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: pg-backup-secret
    namespace: postgres
type: Opaque
stringData:
    aws-access-key-id: ENC[AES256_GCM,data:06smO/u6xQEOputTUF+6QNVXHkY=,iv:qXtVPKRakfkjhP5LYnxcmEpDsa2PJwjVi4TqHVkWN+E=,tag:ZgOc0DprQ9SKupdF0DYzAA==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:KnnhxTmuwm/Bxa/vNMCWk4vTPw3DYlElG+diAGY02cg6EVmA7pbeJQ==,iv:+V+G9XV0NNMlkKl2P9E0vnWh808h/xqFM7zWVeB4x8c=,tag:Vtc8FMdKaYXT5Z0KTlBeag==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSjNhYlFpSmtaWUdYR3Iw
            blpHWUVzaXd5WC81QlV5ZjN5SVppQm0zU2djCktDaWtvMXFCbnZoR3lweXZROEFy
            M2NhcDdSVXpOcFpKaXhLQVlIcEpPMHcKLS0tIFV2a3JKTUlpamtRQTFpdlVLUG5Y
            SHJwR1lHRjh1Y2lQUldlMk5xQWkxOUkKrvRIaM1LvUeF7FOYmqR6JQ13X8PnnQ08
            67BLtw3MFlikcKVxWnVyU1JvjKsVZeqGOJQ0AxufIJBe4Iw9wKsFyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T23:24:34Z"
    mac: ENC[AES256_GCM,data:d7asfw4xRPujfCSr2pwn7s3KKEL7tMBh3W70aBUFnoGdRYejStkRgVd1TSgXS3f3vSxloWIAsAcgWovmBXAqI8Bg9Y4mMw+AJrlNxzQVjhbUyKRAmaflH0uk0aGidmdpvsjpj9hpe+QKsVI8x9I1rK4M+/HZSwwNf+5NJMOjySw=,iv:6Uq9ucLZoKgE91hIQQbmtwLeCwIXK8ykSqWwWLLOm50=,tag:VGKTucVMfAxlUVbMwk2rFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
