# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:AzeM9N36GhQD9EFgK3dj/lxCOD3Z+ao0lFpwwENVRvGA685D,iv:exXEFIGl6GVS1/famYEkidgvDVrZRfS4xD9KFyJTxBY=,tag:SqW4Pss1j8FlPi7Cdq7L+g==,type:str]
    username: ENC[AES256_GCM,data:vaEbGkJuAQ==,iv:nH0lhqdRXtZzgbf1i3Z4jwyYfxSl0vqqa3fcgtMSy8k=,tag:6BcTirm9PuIx1X1fIokL5g==,type:str]
kind: Secret
metadata:
    name: spanner-db-user
    namespace: postgres
type: kubernetes.io/basic-auth
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cmtoSHFzUk5WSlZoTXJ3
            Z04rMGJ2eEUydkJtMEdrRUw3MEtvQ1d2Q1Z3CnhXdVdDY3I3ei82c3BnQjNDdHJK
            dk1jYVJxclZmNXF3VmZKck1lWmZuZm8KLS0tIGt3SlNpaGxFWXZaVkFWdkFlempu
            WVF4dGRKZ01NM2JzTlFLTGtZVTB1dWMK32KHRIFZXi1MnhDyKB0vr9efM8SOk5WC
            Z+KqXPiTXETMmZWbZVuiisDlxIk62P0mfyN7dTj58AgQhREo1rcL3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-19T02:28:47Z"
    mac: ENC[AES256_GCM,data:68bEvacLtrYq3q12f8fWqb2ndxPEwmnk6Gpl1RJaSRsLwSB654GGw1c/FG3ZDBEM8yeJ9+FCkceypseihamcUGQzqwCbGfwk7tM79PqHMoz6UcZtLeqYrW+/0zNh67sH84YDhw00ZfTuqn5NbTElYk9A+B0QDI83t2McGZ7GV2s=,iv:l5DKr9LeSxWKo4FMH6APU2swi2oJzDcSfmhVKVZcS+g=,tag:pthDnUt/3XWUhKqWHmq8FA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
