---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./auth-policy.yaml
  - ./certificate.yaml
  - ./ingress-class.yaml
  - ./request-authentication.yaml
  - ./gateway.yaml
