# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/secret.json
# https://kubernetes.io/docs/concepts/configuration/secret/
apiVersion: v1
kind: Secret
metadata:
    name: atuin-secret
    namespace: atuin
type: Opaque
stringData:
    ATUIN_DB_URI: ENC[AES256_GCM,data:IA2nTSL+e7FfQ19Tc2MejDDMXk0sT8anrZuoXyTUbFjKPj1FeZEdR5X0RJuT9nGVLzKSXwBGdYn6KYRTLTyXiyuEge6THjPn33g=,iv:Ac4yjbPrU5SNzJ46aRalVwrBCIeKARROsRUpuZlVgbk=,tag:wnHOLZawfg4g8Nc1IhS2MQ==,type:str]
    ATUIN_OPEN_REGISTRATION: ENC[AES256_GCM,data:30FyCw==,iv:wG/rbzRHpe+DXk6TjDmHgNKPQ2Z19/iWOYsCJ4Y31dA=,tag:M3E71iLcXxq4FKkITahNsA==,type:str]
    ATUIN_DB_USERNAME: ENC[AES256_GCM,data:sKAKy7E=,iv:kjaZ6DTE5wzMw9qn1l7VUAmahWtrvAG7uGaD4c5uMX0=,tag:j6OjpsyI/1oIFkFUcJmclQ==,type:str]
    ATUIN_DB_PASSWORD: ENC[AES256_GCM,data:YmWms+LbGaunoITr9V9w,iv:gAC0IKepqhn8SCS+zm60REiUtb9Hek/7RahUm9J3Gug=,tag:xuI1ehEhVKXU0cVYkKCW4g==,type:str]
    ATUIN_DB_HOST: ENC[AES256_GCM,data:3moqbtfueOfMceQrzpcqn0Qht5H3x9RStwT45miZavjWHjA=,iv:UImy/cyXEntGhm92/M+GtRsUiC5gVR0RGRQTcLcARNg=,tag:qd9Y0JiwLSdizcWEh+mRGg==,type:str]
    ATUIN_HOST: ENC[AES256_GCM,data:Ws68JQo72g==,iv:TZl+PG0Fr2kXd6CF9T/vCdSC2XY8ZY9Xqfij6UcGEQg=,tag:nW7iAo4WEWMwGVy1HtBA4g==,type:str]
    ATUIN_PORT: ENC[AES256_GCM,data:X1YtQQ==,iv:ZtRTWd5GYv32PDws/anMBiAC56YfrtDIlwYMSAp6cS0=,tag:F2alwjNpiV2ue44wKVJh5A==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:blsqLaI=,iv:xb8dfJyB9AZSYwm6IfIyxysv9tvh0u88ADlYCBDO1rk=,tag:8ZAnJ8BwbGzcHo52dxD0ZA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:qcjKLO4cmBcCcFHdIu2/X+IZ0UpoydOKSZhTaI4VR//crNE=,iv:vrQQ12e5NvXinG0NrGBkzWotSonIc6VFWPYCbTe/o8k=,tag:iVBU9XJuf1PsDSvnwGcA5A==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:w776lTQ=,iv:r2vs5lJ4asutHZGb+DCSyp10gZ+8cICpFzWxDBFg5gU=,tag:yOQyk73BY8+HKIu2R+BP+Q==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:JXjAQLCTsM1ishb1uDLJ,iv:v74HzlKjo2SpWDek+W5GlCEBZjm81uYQ7IKkKnW15CI=,tag:oOK1XXSzUgUi6v6NogfL7g==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:9OZusYllq9BF6RYfNfAj92utNZibvvW2Dw==,iv:2iunAiW5TCGom0ZmNNcE2K3fXu928vc35CfkAHCgEgE=,tag:uBuV/ldcnojauYCGutMYsQ==,type:str]
sops:
    age:
        - recipient: age10vdnx33zyesr04jeeepdungzmzhj3572pz9ccev3zsj6dxhvz49slagxdv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaZEUvSllNOERQUy9WUWI5
            Zjl2T0s0Z1pneDNpaHNlMEMrMm1kWFpHWWpzCk5oL1JPOEJLckJYMHBjRlBSd0hE
            ZlFicDRUQk5ITWswNEdPTHpVOTdyMWMKLS0tIFBpN2U1SWI4SkRYSTE5QXd0RVk0
            OXFKeGdXL2JHbWdFak1CeW1PeitJRDAK8c05Kz5lvDipbmM7/qVmHziE6T1qAS03
            8Iqe1mqjZY4xnSq19bdPxtE+jF4XF45mpQryuV2gXtzHjbPvZL67vQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-20T06:28:11Z"
    mac: ENC[AES256_GCM,data:0qsN6xI95ziG1pNygVJjm3pzrp2LWQtCu2P8U+C2GfC+URT911W8dbe1T8J6k9tXQYGNpBFp5jOs5vFMItZhqB6BSABSJcLtgIJqL5WRZL3ybh2QPWWKvl/tOTpAeN0XgQ/uo9I/PoZzimviSuUjZmJcGt9PMWmjSBHAE45EK0k=,iv:XHA22OlszKxd/GJ1RqRyCHWnzCOIM3oTmOSd6a/arIk=,tag:EPqoes046s9kEQtF8hdsQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
