---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.config.k8s.io/kustomization_v1beta1.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pod-security.yaml
  - ./network-policies.yaml
  - ./resource-limits.yaml
  - ./git-push-token-replication.yaml
