# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.config.k8s.io/kustomization_v1beta1.json
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./addons
  - ./addons/ks.yaml
  - ./weave-gitops/ks.yaml
  - ./image-automation/ks.yaml
  - ./image-automation/resources-ks.yaml
