# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/v1/service.json
---
apiVersion: v1
kind: Service
metadata:
  name: &app console
  namespace: redpanda
  labels:
    app.kubernetes.io/name: *app
    app.kubernetes.io/instance: *app
  annotations:
    external-dns.alpha.kubernetes.io/hostname: redpanda.${SECRET_DOMAIN}
    tailscale.com/expose: "true"
    tailscale.com/hostname: redpanda-console
    lbipam.cilium.io/ips: 192.168.1.244
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: console
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/instance: console
    app.kubernetes.io/name: console
