---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller
  - ./arangodb
  - ./cnpg-system
  - ./dragonflydb
  - ./elastic
  - ./flink
  - ./kubevirt
  - ./rabbitmq-operator
  - ./redpanda
  - ./rook-ceph
