# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/storage.k8s.io/v1/storageclass.json
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  server: 192.168.1.89
  share: /
provisioner: nfs.csi.k8s.io
mountOptions: [hard, noatime, vers=4.0, rw]
reclaimPolicy: Delete
volumeBindingMode: Immediate
